# categorical_encoding

- One Hot Encoding
- Ordinal encoding

### `One hot encoding` can be performed in the nominal data where every entity having equal importance

In [2]:
import seaborn as sb

In [84]:
df=sb.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [85]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

## Identifing the types

### For sex,smoker,day, time, we use the nominal, for the SIZE WE USE the ordinal conversion

In [86]:
Obj2=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
Smoke=Obj2.fit_transform(df.smoker.to_frame())
Smoke

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]

## Dimensionality Expansion – Example

### Scenario:
Dimensionality expansion commonly occurs when applying **categorical encoding techniques** such as **One-Hot Encoding** or **Ordinal Encoding** using libraries like *scikit-learn*. These techniques convert categorical data into numerical form so that machine learning algorithms can process it.

### How it works:
For example, if a categorical feature has values like **Yes** and **No**, applying One-Hot Encoding will create separate binary columns:
- One column representing **Yes**
- Another column representing **No**

This results in an increase in the number of features.

### Effect on the dataset:
If a dataset originally contains **7 features**, applying categorical encoding may expand it to **10–18 features**, depending on the number of unique categories. This increase in dimensionality can lead to:
- Larger feature space
- Higher computational cost
- Risk of **overfitting**

### Handling dimensionality expansion:
To control unnecessary feature growth, dimensionality reduction strategies can be applied.  
One common approach is using the parameter:

```python
OneHotEncoder(drop='first')

In [87]:
Obj2=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
Smoke=Obj2.fit_transform(df.smoker.to_frame())
Smoke

     smoker_Yes
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
..          ...
239         0.0
240         1.0
241         1.0
242         0.0
243         0.0

[244 rows x 1 columns]

In [88]:
df.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [89]:
# ---> follow the nominal encoding that is One-hot encoding
df.sex

0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): ['Male', 'Female']

In [90]:
Sex_trans=Obj2.fit_transform(df.sex.to_frame())
Sex_trans

     sex_Male
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
239       1.0
240       0.0
241       1.0
242       1.0
243       0.0

[244 rows x 1 columns]

In [91]:
Sex_trans

     sex_Male
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
239       1.0
240       0.0
241       1.0
242       1.0
243       0.0

[244 rows x 1 columns]

In [92]:
day=Obj2.fit_transform(df.day.to_frame())
day

     day_Sat  day_Sun  day_Thur
0        0.0      1.0       0.0
1        0.0      1.0       0.0
2        0.0      1.0       0.0
3        0.0      1.0       0.0
4        0.0      1.0       0.0
..       ...      ...       ...
239      1.0      0.0       0.0
240      1.0      0.0       0.0
241      1.0      0.0       0.0
242      1.0      0.0       0.0
243      0.0      0.0       1.0

[244 rows x 3 columns]

In [93]:
time=Obj2.fit_transform(df.time.to_frame())
time

     time_Lunch
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
..          ...
239         0.0
240         0.0
241         0.0
242         0.0
243         0.0

[244 rows x 1 columns]

In [115]:
df['size']

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [116]:
def dec_size(para):
    if para<3:
        return 'S'
    elif para<4:
        return 'M'
    else:
        return 'L'

In [117]:
df['size']=df['size'].apply(dec_size)

In [118]:
df['size']

0      S
1      M
2      M
3      S
4      L
      ..
239    M
240    S
241    S
242    S
243    S
Name: size, Length: 244, dtype: object

 # The `categories` is specified in OrdinalEncoder to preserve the natural ranking of categorical values, ensuring the numerical encoding reflects their true hierarchical relationship and avoids misleading the model.

In [124]:
order=['S','M','L']

In [125]:
oe=OrdinalEncoder(categories=[order1]).set_output(transform='pandas')
oe

OrdinalEncoder(categories=[['S', 'M', 'L']])

In [126]:
df['size']

0      S
1      M
2      M
3      S
4      L
      ..
239    M
240    S
241    S
242    S
243    S
Name: size, Length: 244, dtype: object

In [128]:
_size=oe.fit_transform(df[['size']])

In [129]:
_size

     size
0     0.0
1     1.0
2     1.0
3     0.0
4     2.0
..    ...
239   1.0
240   0.0
241   0.0
242   0.0
243   0.0

[244 rows x 1 columns]

In [130]:
from sklearn.compose import ColumnTransformer

In [133]:

CTS=ColumnTransformer([('NOMINAL',Obj2,['sex','smoker','day','time']),('ORDINAL',oe,['size'])], remainder='passthrough').set_output(transform='pandas')

In [134]:
CTS

ColumnTransformer(remainder='passthrough',
                  transformers=[('NOMINAL',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time']),
                                ('ORDINAL',
                                 OrdinalEncoder(categories=[['S', 'M', 'L']]),
                                 ['size'])])

In [136]:
CTS.fit_transform(df[:])

,NOMINAL__sex_Male,NOMINAL__smoker_Yes,NOMINAL__day_Sat,NOMINAL__day_Sun,NOMINAL__day_Thur,NOMINAL__time_Lunch,ORDINAL__size,remainder__total_bill,remainder__tip
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,16.99,1.01
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,10.34,1.66
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,21.01,3.50
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,23.68,3.31
4,0.0,0.0,0.0,1.0,0.0,0.0,2.0,24.59,3.61
...,...,...,...,...,...,...,...,...,...
239,1.0,0.0,1.0,0.0,0.0,0.0,1.0,29.03,5.92
240,0.0,1.0,1.0,0.0,0.0,0.0,0.0,27.18,2.00
241,1.0,1.0,1.0,0.0,0.0,0.0,0.0,22.67,2.00
242,1.0,0.0,1.0,0.0,0.0,0.0,0.0,17.82,1.75
243,0.0,0.0,0.0,0.0,1.0,0.0,0.0,18.78,3.00

In [137]:
df

     total_bill   tip     sex smoker   day    time size
0         16.99  1.01  Female     No   Sun  Dinner    S
1         10.34  1.66    Male     No   Sun  Dinner    M
2         21.01  3.50    Male     No   Sun  Dinner    M
3         23.68  3.31    Male     No   Sun  Dinner    S
4         24.59  3.61  Female     No   Sun  Dinner    L
..          ...   ...     ...    ...   ...     ...  ...
239       29.03  5.92    Male     No   Sat  Dinner    M
240       27.18  2.00  Female    Yes   Sat  Dinner    S
241       22.67  2.00    Male    Yes   Sat  Dinner    S
242       17.82  1.75    Male     No   Sat  Dinner    S
243       18.78  3.00  Female     No  Thur  Dinner    S

[244 rows x 7 columns]