In [1]:
import os
import pandas as pd
import numpy as np

In [3]:
os.getcwd()

'C:\\Users\\chidv\\Batch405\\pandas'

### how many was that python accepts the directories
* Absolute------> Total path, ex: C:\\Users\\chidv\\Batch405\\pandas 
* Relative------> only works when the given file or folder location is in same directory
*                ex: Batch405\pandas

In [4]:
# how to access the diffrent file locations in py thon 
# there are three diffrebt ways to acces the files in python 

#  directly accessing the files

In [5]:
print('C:\\Users\\chidv\\Batch405\\pandas') # the first \ will tells python the consider next one as raw
print('C:Users/chidv/Batch405/pandas') #directly mofify the every address with hand
print(r'C:Users\chidv\Batch405\pandas') # or use raw string dirctly

C:\Users\chidv\Batch405\pandas
C:Users/chidv/Batch405/pandas
C:Users\chidv\Batch405\pandas

In [2]:
## importing the dataFrames from local system 

#car_df=pd.read_csv('car_data.csv') #relative path

car_df=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\car_data.xlsx",sheet_name='car') #Absolute path

In [3]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [8]:
# working with the  properties of padas with this dataset

#properties of the data series
print(" shape of table is :",car_df.shape)
print(" index of table is :",car_df.index)
print(" size of table is :",car_df.size)
print("\n dtypes of table is :",car_df.dtypes) #string is refered object in pandas 
print("\n length of table is :",len(car_df))

 shape of table is : (205, 23)
 index of table is : RangeIndex(start=0, stop=205, step=1)
 size of table is : 4715

 dtypes of table is : Unnamed: 0             int64
make                  object
fuel_type             object
aspiration            object
num_of_doors          object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_of_cylinders      object
engine_size            int64
fuel_system           object
compression_ratio    float64
horsepower            object
peak_rpm              object
city_mpg               int64
highway_mpg            int64
price                 object
dtype: object

 length of table is : 205

In [9]:
print(" shape of table is :",car_df.head(2))
print(" index of table is :",car_df.tail(2))

 shape of table is :    Unnamed: 0         make fuel_type aspiration num_of_doors   body_style  \
0           1  alfa-romero       gas        std          two  convertible
1           2  alfa-romero       gas        std          two  convertible

  drive_wheels engine_location  wheel_base  length  ...  engine_type  \
0          rwd           front        88.6   168.8  ...         dohc
1          rwd           front        88.6   168.8  ...         dohc

   num_of_cylinders  engine_size fuel_system compression_ratio  horsepower  \
0              four          130        mpfi               9.0         111
1              four          130        mpfi               9.0         111

  peak_rpm  city_mpg highway_mpg  price
0     5000        21          27  13495
1     5000        21          27  16500

[2 rows x 23 columns]
 index of table is :      Unnamed: 0   make fuel_type aspiration num_of_doors body_style  \
203         204  volvo    diesel      turbo         four      sedan
204         205  volvo       gas      turbo         four      sedan

    drive_wheels engine_location  wheel_base  length  ...  engine_type  \
203          rwd           front       109.1   188.8  ...          ohc
204          rwd           front       109.1   188.8  ...          ohc

     num_of_cylinders  engine_size fuel_system compression_ratio  horsepower  \
203               six          145         idi              23.0         106
204              four          141        mpfi               9.5         114

    peak_rpm  city_mpg highway_mpg  price
203     4800        26          27  22470
204     5400        19          25  22625

[2 rows x 23 columns]

In [2]:
HR=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\visualizationDF\HRDataset_v14.csv")
HR

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

## `reset_option` inorder to print the all the rows in data set use the reset_option

In [16]:
pd.reset_option('display.max_rows')
HR

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [10]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         205 non-null    int64
 1   make               205 non-null    object
 2   fuel_type          205 non-null    object
 3   aspiration         205 non-null    object
 4   num_of_doors       205 non-null    object
 5   body_style         205 non-null    object
 6   drive_wheels       205 non-null    object
 7   engine_location    205 non-null    object
 8   wheel_base         205 non-null    float64
 9   length             205 non-null    float64
 10  width              205 non-null    float64
 11  height             205 non-null    float64
 12  curb_weight        205 non-null    int64
 13  engine_type        205 non-null    object
 14  num_of_cylinders   205 non-null    object
 15  engine_size        205 non-null    int64
 16  fuel_system        205 non-null    object
 17  compression_ratio  205 non-null    float64
 18  horsepower         205 non-null    object
 19  peak_rpm           205 non-null    object
 20  city_mpg           205 non-null    int64
 21  highway_mpg        205 non-null    int64
 22  price              205 non-null    object
dtypes: float64(5), int64(5), object(13)
memory usage: 37.0+ KB

## Summary/Descriptive Statistics of a Data frame

#### Diffrience between the summary and Descriptive statistics is 
* `descriptive` it is used to to extract the analasys of numerical entities in table
*             (like mean, median, mode, standard deviation, min, max, etc.)
* `summary` it is used to extract the analysis of string or object entities in table

In [11]:
car_table=pd.read_csv(r"C:\Users\chidv\Downloads\car_data.csv")

In [12]:
car_table.describe()  #descriptive analysis

,Unnamed: 0,wheel_base,length,width,height,curb_weight,engine_size,compression_ratio,city_mpg,highway_mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,59.322565,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,1.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,52.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,103.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,154.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,205.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [13]:
car_table.describe(include=np.object_) #summary analysis includes text values tooo

,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,engine_type,num_of_cylinders,fuel_system,horsepower,peak_rpm,price
count,205,205,205,205,205,205,205,205,205,205,205,205,205
unique,22,2,2,3,5,3,2,7,7,8,60,24,187
top,toyota,gas,std,four,sedan,fwd,front,ohc,four,mpfi,68,5500,?
freq,32,185,168,114,96,120,202,148,159,94,19,37,4

In [14]:
car_table.describe(include=float)

       wheel_base      length       width      height  compression_ratio
count  205.000000  205.000000  205.000000  205.000000         205.000000
mean    98.756585  174.049268   65.907805   53.724878          10.142537
std      6.021776   12.337289    2.145204    2.443522           3.972040
min     86.600000  141.100000   60.300000   47.800000           7.000000
25%     94.500000  166.300000   64.100000   52.000000           8.600000
50%     97.000000  173.200000   65.500000   54.100000           9.000000
75%    102.400000  183.100000   66.900000   55.500000           9.400000
max    120.900000  208.100000   72.300000   59.800000          23.000000

In [15]:
car_table.describe(include=int)

       Unnamed: 0  curb_weight  engine_size    city_mpg  highway_mpg
count  205.000000   205.000000   205.000000  205.000000   205.000000
mean   103.000000  2555.565854   126.907317   25.219512    30.751220
std     59.322565   520.680204    41.642693    6.542142     6.886443
min      1.000000  1488.000000    61.000000   13.000000    16.000000
25%     52.000000  2145.000000    97.000000   19.000000    25.000000
50%    103.000000  2414.000000   120.000000   24.000000    30.000000
75%    154.000000  2935.000000   141.000000   30.000000    34.000000
max    205.000000  4066.000000   326.000000   49.000000    54.000000

In [16]:
car_table.describe(include='all')  # gives analysis for the all types of data int,float,str

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,205.000000,205,205,205,205,205,205,205,205.000000,205.000000,...,205,205,205.000000,205,205.000000,205,205,205.000000,205.000000,205
unique,NaN,22,2,2,3,5,3,2,NaN,NaN,...,7,7,NaN,8,NaN,60,24,NaN,NaN,187
top,NaN,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,...,ohc,four,NaN,mpfi,NaN,68,5500,NaN,NaN,?
freq,NaN,32,185,168,114,96,120,202,NaN,NaN,...,148,159,NaN,94,NaN,19,37,NaN,NaN,4
mean,103.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,...,NaN,NaN,126.907317,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,59.322565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,...,NaN,NaN,41.642693,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,...,NaN,NaN,61.000000,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,52.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,...,NaN,NaN,97.000000,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,103.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,...,NaN,NaN,120.000000,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,154.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,...,NaN,NaN,141.000000,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,205.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,...,NaN,NaN,326.000000,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

## NaN (Not a Number)

`NaN` signifies the absence of a valid value in a dataset.  
It is commonly encountered in data analysis and can arise due to several reasons:

### Causes of NaN:
- **Data entry errors**  
  e.g., Manual input mistakes that leave cells blank or incorrect.

- **Incomplete or missing data**  
  e.g., Data collected from forms or sensors may have gaps.

- **Data conversion issues**  
  e.g., Trying to convert a non-numeric string like `'abc'` into a number.

- **Mathematical operations that result in undefined values**  
  e.g., Division by zero (`0/0`) or applying math functions on string values.

> NaN values can affect calculations like mean, sum, or correlations, and are often handled using imputation, filtering, or replacement strategies in data preprocessing.

# creating the datframe exel data

In [43]:
table2=pd.read_excel('car_data.xlsx') # diffrent file it only containing car data

In [44]:
table2.head() #data coming from exel

Empty DataFrame
Columns: []
Index: []

## When you use pandas.read_excel() without specifying the sheet name, it defaults to reading only the first sheet with data. If the first sheet is empty, it might skip or return an empty DataFrame

In [57]:
#you can able to load the spectific sheets from the data
#supposuse if you want to know how many sheets that you have 
filenames=pd.ExcelFile(r"C:\Users\chidv\Downloads\Data_sets\car_data.xlsx")
print(filenames.sheet_names)

['Sheet1', 'Sheet2', 'car_data.xlsx', 'Sheet3', 'Sheet4', 'Sheet5']

In [58]:
## When you use pandas.read_excel() without specifying the sheet name, it defaults to reading only the first sheet with data. If the first sheet is empty, it might skip or return an empty DataFrame
table_exel=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\car_data.xlsx")
table_exel # results empty bcoz first sheet is empty

Empty DataFrame
Columns: []
Index: []

In [60]:
# if you want to print the specific sheet the  iam printing car data 
table_exel=pd.read_excel('car_data.xlsx',sheet_name='car_data')
table_exel.head()

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,152.0,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450

### Loading Text Data from Files

When working with **text files** that contain **tabular data**, you can load them into **DataFrames** using the correct **delimiter** that separates the values in each row.

There are several common types of delimiter-separated files:

- `\t` → **Tab-separated** files  
- `,` → **Comma-separated** (CSV) files  
- `|` → **Pipe-separated** files  
- `;` → **Semicolon-separated** files

In [53]:
tab_wala=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\tab_delimiters.tsv", delimiter='\t')

In [54]:
tab_wala

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Email,JoinDate
0,1,Alice,28,Female,Engineer,85000,New York,USA,alice@example.com,2020-05-15
1,2,Bob,32,Male,Doctor,120000,Los Angeles,USA,bob@example.com,2019-11-22
2,3,Carol,24,Female,Teacher,45000,Chicago,USA,carol@example.com,2021-03-10
3,4,Dave,45,Male,Manager,95000,Houston,USA,dave@example.com,2018-07-05
4,5,Eve,29,Female,Designer,60000,Phoenix,USA,eve@example.com,2022-01-18
5,6,Frank,35,Male,Lawyer,110000,Philadelphia,USA,frank@example.com,2017-09-30
6,7,Grace,31,Female,Nurse,55000,San Antonio,USA,grace@example.com,2020-08-12
7,8,Henry,40,Male,Architect,90000,San Diego,USA,henry@example.com,2016-04-25
8,9,Ivy,27,Female,Developer,80000,Dallas,USA,ivy@example.com,2021-07-14
9,10,Jack,33,Male,Consultant,75000,San Jose,USA,jack@example.com,2019-02-28
10,11,Kara,26,Female,Writer,50000,Austin,USA,kara@example.com,2022-05-09
11,12,Leo,38,Male,Engineer,95000,Jacksonville,USA,leo@example.com,2018-10-17
12,13,Mia,30,Female,Doctor,130000,San Francisco,USA,mia@example.com,2017-12-03
13,14,Noah,42,Male,Professor,70000,Columbus,USA,noah@example.com,2016-08-21
14,15,Olivia,25,Female,Analyst,65000,Charlotte,USA,olivia@example.com,2021-11-07
15,16,Paul,36,Male,Manager,100000,Indianapolis,USA,paul@example.com,2019-06-19
16,17,Quinn,29,Female,Designer,62000,Seattle,USA,quinn@example.com,2020-09-23
17,18,Ryan,34,Male,Lawyer,115000,Denver,USA,ryan@example.com,2018-03-16
18,19,Sophia,28,Female,Teacher,48000,Washington,USA,sophia@example.com,2022-02-11
19,20,Tom,41,Male,Architect,92000,Boston,USA,tom@example.com,2017-05-28
20,21,Uma,27,Female,Developer,82000,Nashville,USA,uma@example.com,2021-04-05
21,22,Victor,39,Male,Consultant,77000,Baltimore,USA,victor@example.com,2019-10-30
22,23,Wendy,26,Female,Writer,52000,Memphis,USA,wendy@example.com,2022-07-15
23,24,Xander,37,Male,Engineer,97000,Portland,USA,xander@example.com,2018-01-12
24,25,Yara,31,Female,Doctor,135000,Oklahoma City,USA,yara@example.com,2017-11-08
25,26,Zack,43,Male,Professor,72000,Las Vegas,USA,zack@example.com,2016-09-24
26,27,Ava,24,Female,Analyst,67000,Louisville,USA,ava@example.com,2021-12-02
27,28,Ben,35,Male,Manager,105000,Milwaukee,USA,ben@example.com,2019-04-14
28,29,Cora,30,Female,Designer,64000,Albuquerque,USA,cora@example.com,2020-10-07
29,30,Duke,44,Male,Lawyer,118000,Tucson,USA,duke@example.com,2018-06-20

In [55]:
pipe_wala=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\pipe.psv", delimiter='|')

In [56]:
pipe_wala

,ID,Name,Age,Gender,Occupation,Salary,City,Country,Email,JoinDate
0,1,Alice,28,Female,Engineer,85000,New York,USA,alice@example.com,2020-05-15
1,2,Bob,32,Male,Doctor,120000,Los Angeles,USA,bob@example.com,2019-11-22
2,3,Carol,24,Female,Teacher,45000,Chicago,USA,carol@example.com,2021-03-10
3,4,Dave,45,Male,Manager,95000,Houston,USA,dave@example.com,2018-07-05
4,5,Eve,29,Female,Designer,60000,Phoenix,USA,eve@example.com,2022-01-18
5,6,Frank,35,Male,Lawyer,110000,Philadelphia,USA,frank@example.com,2017-09-30
6,7,Grace,31,Female,Nurse,55000,San Antonio,USA,grace@example.com,2020-08-12
7,8,Henry,40,Male,Architect,90000,San Diego,USA,henry@example.com,2016-04-25
8,9,Ivy,27,Female,Developer,80000,Dallas,USA,ivy@example.com,2021-07-14
9,10,Jack,33,Male,Consultant,75000,San Jose,USA,jack@example.com,2019-02-28
10,11,Kara,26,Female,Writer,50000,Austin,USA,kara@example.com,2022-05-09
11,12,Leo,38,Male,Engineer,95000,Jacksonville,USA,leo@example.com,2018-10-17
12,13,Mia,30,Female,Doctor,130000,San Francisco,USA,mia@example.com,2017-12-03
13,14,Noah,42,Male,Professor,70000,Columbus,USA,noah@example.com,2016-08-21
14,15,Olivia,25,Female,Analyst,65000,Charlotte,USA,olivia@example.com,2021-11-07
15,16,Paul,36,Male,Manager,100000,Indianapolis,USA,paul@example.com,2019-06-19
16,17,Quinn,29,Female,Designer,62000,Seattle,USA,quinn@example.com,2020-09-23
17,18,Ryan,34,Male,Lawyer,115000,Denver,USA,ryan@example.com,2018-03-16
18,19,Sophia,28,Female,Teacher,48000,Washington,USA,sophia@example.com,2022-02-11
19,20,Tom,41,Male,Architect,92000,Boston,USA,tom@example.com,2017-05-28
20,21,Uma,27,Female,Developer,82000,Nashville,USA,uma@example.com,2021-04-05
21,22,Victor,39,Male,Consultant,77000,Baltimore,USA,victor@example.com,2019-10-30
22,23,Wendy,26,Female,Writer,52000,Memphis,USA,wendy@example.com,2022-07-15
23,24,Xander,37,Male,Engineer,97000,Portland,USA,xander@example.com,2018-01-12
24,25,Yara,31,Female,Doctor,135000,Oklahoma City,USA,yara@example.com,2017-11-08
25,26,Zack,43,Male,Professor,72000,Las Vegas,USA,zack@example.com,2016-09-24
26,27,Ava,24,Female,Analyst,67000,Louisville,USA,ava@example.com,2021-12-02
27,28,Ben,35,Male,Manager,105000,Milwaukee,USA,ben@example.com,2019-04-14
28,29,Cora,30,Female,Designer,64000,Albuquerque,USA,cora@example.com,2020-10-07
29,30,Duke,44,Male,Lawyer,118000,Tucson,USA,duke@example.com,2018-06-20

### Exporting the dataframes

In [63]:
# here iam using csv and exel
car_df.to_excel( r'C:\Users\chidv\Downloads\Data_sets\exported.xlsx',index=False) #if you given the index ==false it will prevents the adding the outer index
car_df.to_csv( r'C:\Users\chidv\Downloads\Data_sets\exported2.csv',index=False)
#check the addresses you will find the files

### operations on the dataframes

In [69]:
#operations on the dataframes
for every in dir(car_df):
    if(every.startswith('_')):
        pass
    else:
        print(every, end=' , ')

T , abs , add , add_prefix , add_suffix , agg , aggregate , align , all , any , apply , applymap , asfreq , asof , aspiration , assign , astype , at , at_time , attrs , axes , backfill , between_time , bfill , body_style , bool , boxplot , city_mpg , clip , columns , combine , combine_first , compare , compression_ratio , convert_dtypes , copy , corr , corrwith , count , cov , cummax , cummin , cumprod , cumsum , curb_weight , describe , diff , div , divide , dot , drive_wheels , drop , drop_duplicates , droplevel , dropna , dtypes , duplicated , empty , engine_location , engine_size , engine_type , eq , equals , eval , ewm , expanding , explode , ffill , fillna , filter , first , first_valid_index , flags , floordiv , from_dict , from_records , fuel_system , fuel_type , ge , get , groupby , gt , head , height , highway_mpg , hist , horsepower , iat , idxmax , idxmin , iloc , index , infer_objects , info , insert , interpolate , isetitem , isin , isna , isnull , items , iterrows , itertuples , join , keys , kurt , kurtosis , last , last_valid_index , le , length , loc , lt , make , map , mask , max , mean , median , melt , memory_usage , merge , min , mod , mode , mul , multiply , ndim , ne , nlargest , notna , notnull , nsmallest , num_of_cylinders , num_of_doors , nunique , pad , pct_change , peak_rpm , pipe , pivot , pivot_table , plot , pop , pow , price , prod , product , quantile , query , radd , rank , rdiv , reindex , reindex_like , rename , rename_axis , reorder_levels , replace , resample , reset_index , rfloordiv , rmod , rmul , rolling , round , rpow , rsub , rtruediv , sample , select_dtypes , sem , set_axis , set_flags , set_index , shape , shift , size , skew , sort_index , sort_values , squeeze , stack , std , style , sub , subtract , sum , swapaxes , swaplevel , tail , take , to_clipboard , to_csv , to_dict , to_excel , to_feather , to_gbq , to_hdf , to_html , to_json , to_latex , to_markdown , to_numpy , to_orc , to_parquet , to_period , to_pickle , to_records , to_sql , to_stata , to_string , to_timestamp , to_xarray , to_xml , transform , transpose , truediv , truncate , tz_convert , tz_localize , unstack , update , value_counts , values , var , wheel_base , where , width , xs ,

In [76]:
car_df.sum(numeric_only=True) #it will concatinates even string if we not given condition numeric_only=True

Unnamed: 0            21115.00
wheel_base            20245.10
length                35680.10
width                 13511.10
height                11013.60
curb_weight          523891.00
engine_size           26016.00
compression_ratio      2079.22
city_mpg               5170.00
highway_mpg            6304.00
dtype: float64

In [77]:
car_df.count()

Unnamed: 0           205
make                 205
fuel_type            205
aspiration           205
num_of_doors         205
body_style           205
drive_wheels         205
engine_location      205
wheel_base           205
length               205
width                205
height               205
curb_weight          205
engine_type          205
num_of_cylinders     205
engine_size          205
fuel_system          205
compression_ratio    205
horsepower           205
peak_rpm             205
city_mpg             205
highway_mpg          205
price                205
dtype: int64

In [82]:
car_df.min() # it will returns the min index row values

Unnamed: 0                     1
make                 alfa-romero
fuel_type                 diesel
aspiration                   std
num_of_doors                   ?
body_style           convertible
drive_wheels                 4wd
engine_location            front
wheel_base                  86.6
length                     141.1
width                       60.3
height                      47.8
curb_weight                 1488
engine_type                 dohc
num_of_cylinders           eight
engine_size                   61
fuel_system                 1bbl
compression_ratio            7.0
horsepower                   100
peak_rpm                    4150
city_mpg                      13
highway_mpg                   16
price                      10198
dtype: object

In [83]:
car_df.max() # it will returns the max index row values

Unnamed: 0             205
make                 volvo
fuel_type              gas
aspiration           turbo
num_of_doors           two
body_style           wagon
drive_wheels           rwd
engine_location       rear
wheel_base           120.9
length               208.1
width                 72.3
height                59.8
curb_weight           4066
engine_type          rotor
num_of_cylinders       two
engine_size            326
fuel_system           spfi
compression_ratio     23.0
horsepower               ?
peak_rpm                 ?
city_mpg                49
highway_mpg             54
price                    ?
dtype: object

In [87]:
car_df.nunique()

Unnamed: 0           205
make                  22
fuel_type              2
aspiration             2
num_of_doors           3
body_style             5
drive_wheels           3
engine_location        2
wheel_base            53
length                75
width                 44
height                49
curb_weight          171
engine_type            7
num_of_cylinders       7
engine_size           44
fuel_system            8
compression_ratio     32
horsepower            60
peak_rpm              24
city_mpg              29
highway_mpg           30
price                187
dtype: int64

## Extracting only the single column


* if any of column label having gap b/w them used  `df['column name']`
* else directly use this (makesure no gaps b/w column labels): `df.column_name`

In [88]:
car_df.make

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [92]:
car_df['height']

0      48.8
1      48.8
2      52.4
3      54.3
4      54.3
       ...
200    55.5
201    55.5
202    55.5
203    55.5
204    55.5
Name: height, Length: 205, dtype: float64

In [106]:
# if you extract the single cloumn the type of the undergoing data is series so 
# you can apply series proerties along with predefined operations
car_df.num_of_doors.unique()

array(['two', 'four', '?'], dtype=object)

In [145]:
car_df.num_of_doors.nunique()

3

In [103]:
dir(car_df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'aspiration',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'body_style',
 'bool',
 'boxplot',
 'city_mpg',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'compression_ratio',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'curb_weight',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drive_wheels',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'engine_location',
 'engine_size',
 'engine_type',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'fuel_system',
 'fuel_type',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'height',
 'highway_mpg',
 'hist',
 'horsepower',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'length',
 'loc',
 'lt',
 'make',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'num_of_cylinders',
 'num_of_doors',
 'nunique',
 'pad',
 'pct_change',
 'peak_rpm',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'wheel_base',
 'where',
 'width',
 'xs']

In [144]:
car_df.make

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [110]:
car_df.make.index

RangeIndex(start=0, stop=205, step=1)

In [111]:
car_df.make.values

array(['alfa-romero', 'alfa-romero', 'alfa-romero', 'audi', 'audi',
       'audi', 'audi', 'audi', 'audi', 'audi', 'bmw', 'bmw', 'bmw', 'bmw',
       'bmw', 'bmw', 'bmw', 'bmw', 'chevrolet', 'chevrolet', 'chevrolet',
       'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge',
       'dodge', 'dodge', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'isuzu', 'isuzu', 'isuzu', 'isuzu', 'jaguar', 'jaguar',
       'jaguar', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'mercedes-benz',
       'mercedes-benz', 'mercedes-benz', 'mercedes-benz', 'mercedes-benz',
       'mercedes-benz', 'mercedes-benz', 'mercedes-benz', 'mercury',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'peugot', 'peugot', 'peugot', 'peugot', 'peugot',
       'peugot', 'peugot', 'peugot', 'peugot', 'peugot', 'peugot',
       'plymouth', 'plymouth', 'plymouth', 'plymouth', 'plymouth',
       'plymouth', 'plymouth', 'porsche', 'porsche', 'porsche', 'porsche',
       'porsche', 'renault', 'renault', 'saab', 'saab', 'saab', 'saab',
       'saab', 'saab', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volvo', 'volvo', 'volvo', 'volvo',
       'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo'],
      dtype=object)

In [121]:
car_df.length.max()

np.float64(208.1)

In [123]:
car_df.price.sum()

'134951650016500139501745015250177101892023875?1643016925209702110524565307604131536880515162956575557263777957622966927609855889211296464796855539965297129729572957895909588451029512945103456785??11048322503555036000519560956795669573951094511845136451564588458495105951024510795112451828018344255522824828176316003418435056409604540016503538961896669768999598499126291486914489698981899279927954997099664968497349729977997499799982498949954913499143991349917199196991839911900132001244013860155801690016695170751663017950181505572795762296692760989211276422018325283402837028?9295989511850121701504015510181501862051187053760371267775996092331125974631019880131169453486338648869187898877869387198789877887738835892588058823892989538844996399989111991154917669894810698998810898112481655815998156901575077757975799581958495949599951159599801329513845122901294013415159851651518420189501684519045214852247022625'

In [128]:
car_df.make.value_counts()

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
subaru           12
volkswagen       12
volvo            11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

In [126]:
car_df.make.value_counts().index

Index(['toyota', 'nissan', 'mazda', 'mitsubishi', 'honda', 'subaru',
       'volkswagen', 'volvo', 'peugot', 'dodge', 'mercedes-benz', 'bmw',
       'audi', 'plymouth', 'saab', 'porsche', 'isuzu', 'alfa-romero',
       'chevrolet', 'jaguar', 'renault', 'mercury'],
      dtype='object', name='make')

In [127]:
car_df.make.value_counts().values

array([32, 18, 17, 13, 13, 12, 12, 11, 11,  9,  8,  8,  7,  7,  6,  5,  4,
        3,  3,  3,  2,  1])

## Task: get the value counts & unique from -
* engine_type, num_of_cylinders,fuel_system, drive_wheels,body_style

In [146]:
print(car_df.engine_type.value_counts())
print('---'*20)
print(car_df.engine_type.unique())
print(car_df.engine_type.nunique())

engine_type
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: count, dtype: int64
------------------------------------------------------------
['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']
7

In [138]:
print(car_df.num_of_cylinders.value_counts())
print('---'*20)
print(car_df.num_of_cylinders.unique())

num_of_cylinders
four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: count, dtype: int64
------------------------------------------------------------
['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']

In [137]:
print(car_df.fuel_system.value_counts())
print('---'*20)
print(car_df.fuel_system.unique())

fuel_system
mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: count, dtype: int64
------------------------------------------------------------
['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']

In [139]:
print(car_df.drive_wheels.value_counts())
print('---'*20)
print(car_df.drive_wheels.unique())

drive_wheels
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64
------------------------------------------------------------
['rwd' 'fwd' '4wd']

In [140]:
print(car_df.body_style.value_counts())
print('---'*20)
print(car_df.body_style.unique())

body_style
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64
------------------------------------------------------------
['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']

### Get the percentage of each car type by Body style

In [168]:

for i in range(len(car_df.body_style.value_counts())):
    print(f"car type is :{car_df.body_style.value_counts().index[i]} \n  and the percentage amoung the car are {(((car_df.body_style.value_counts().values[i])/(len(car_df)))*100):.2f}%")

car type is :sedan
  and the percentage amoung the car are 46.83%
car type is :hatchback
  and the percentage amoung the car are 34.15%
car type is :wagon
  and the percentage amoung the car are 12.20%
car type is :hardtop
  and the percentage amoung the car are 3.90%
car type is :convertible
  and the percentage amoung the car are 2.93%

In [162]:
len(car_df)

205

In [142]:
car_df.body_style.p

0      convertible
1      convertible
2        hatchback
3            sedan
4            sedan
          ...
200          sedan
201          sedan
202          sedan
203          sedan
204          sedan
Name: body_style, Length: 205, dtype: object

In [18]:
car_df.head()

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450

In [4]:
car_df.describe()

,Unnamed: 0,wheel_base,length,width,height,curb_weight,engine_size,compression_ratio,city_mpg,highway_mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,59.322565,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,1.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,52.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,103.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,154.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,205.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [8]:
car_df.engine_size.quantile([0.25,0.75])

0.25     97.0
0.75    141.0
Name: engine_size, dtype: float64