In [2]:
import pandas as pd  
import numpy as np
import seaborn as sb
import os 

import warnings 
warnings.filterwarnings("ignore")

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Five things we care About DateTime

- pd.to_datetime() + format codes
- pd.Timedelta
- pd.to_periods +codes
- pd. datarange

In [5]:
lod_df=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\Server_log_file.txt")
lod_df

,datetime,server_id,cpu_utilization,free_memory,session_count
0,2019-03-06 00:00:00,100,0.40,0.54,52
1,2019-03-06 01:00:00,100,0.49,0.51,58
2,2019-03-06 02:00:00,100,0.49,0.54,53
3,2019-03-06 03:00:00,100,0.44,0.56,49
4,2019-03-06 04:00:00,100,0.42,0.52,54
...,...,...,...,...,...
40795,2019-04-08 19:00:00,149,0.73,0.20,81
40796,2019-04-08 20:00:00,149,0.75,0.25,83
40797,2019-04-08 21:00:00,149,0.80,0.26,82
40798,2019-04-08 22:00:00,149,0.75,0.29,82
40799,2019-04-08 23:00:00,149,0.75,0.24,80

In [183]:
#Acessing Current time stamp
from datetime import datetime
today=datetime.now()
print(today)

2025-09-02 17:52:51.470974

# Date time in pandas

- Python that will understands date in yyyy-mm-dd format by default

In [9]:
(lod_df.datetime).dtype

dtype('O')

In [ ]:
# so above datetime column in string format so we need to convert datetime

In [12]:
lod_df.datetime=pd.to_datetime(lod_df.datetime)

In [13]:
print(lod_df.datetime,type(lod_df.datetime))

0       2019-03-06 00:00:00
1       2019-03-06 01:00:00
2       2019-03-06 02:00:00
3       2019-03-06 03:00:00
4       2019-03-06 04:00:00
                ...
40795   2019-04-08 19:00:00
40796   2019-04-08 20:00:00
40797   2019-04-08 21:00:00
40798   2019-04-08 22:00:00
40799   2019-04-08 23:00:00
Name: datetime, Length: 40800, dtype: datetime64[ns] <class 'pandas.core.series.Series'>

In [14]:
# now try to convert date manuallu
x=pd.to_datetime('02-09-2025')
x  # the main problem is by default it is taking  mm-dd-yyyy format

Timestamp('2025-02-09 00:00:00')

## Formating in datetime

In [18]:
x=pd.to_datetime('02-09-2025',format='%d-%m-%Y')
x

Timestamp('2025-09-02 00:00:00')

##  Cheat code 'date' table 
- %d -------> Represents Day in number 
- %m -------> Represents months in number
- %Y -------> Represents year in full ex :2025
- %y -------> Represents year in Short ex :25
- %B -------> Represents Full Month name 
- %b -------> Represents Short Month name
- %a -------> Represents Full Day name
- %A -------> Represents Short Day name

##  Cheat code 'Time ' table 
- %H -------> Represents hours in 12 hr format 
- %I -------> Represents hours in 24 hr format 
- %p -------> Represents AM/PM
- %M -------> Represents Minute 
- %S -------> Represents Seconds `

In [23]:
pd.to_datetime("09-03-2019",format='%d-%m-%Y')

Timestamp('2019-03-09 00:00:00')

In [27]:
pd.to_datetime('Sep 3 2025',format='%b %d %Y')

Timestamp('2025-09-03 00:00:00')

In [32]:
#SOMe Examples to code converts 
# make code that py dunderstands the exact format in text
s1 = "Thursday, March 28, 2024 03:45:30 PM" 
s2 = 'Thursday, 28-November-2024'

In [40]:
pd.to_datetime(s1,format=('%A, %B %d, %Y %H:%M:%S %p'))

Timestamp('2024-03-28 03:45:30')

## dayfirst

In [41]:
pd.to_datetime('09-03-2019')

Timestamp('2019-09-03 00:00:00')

In [42]:
#Simply Inorder to remove error without using format use dayfirst=True 
pd.to_datetime('09-03-2019',dayfirst=True)

Timestamp('2019-03-09 00:00:00')

## Extracting the components in the DateTime stamp

In [67]:
ts=lod_df[['datetime']]
ts

                 datetime
0     2019-03-06 00:00:00
1     2019-03-06 01:00:00
2     2019-03-06 02:00:00
3     2019-03-06 03:00:00
4     2019-03-06 04:00:00
...                   ...
40795 2019-04-08 19:00:00
40796 2019-04-08 20:00:00
40797 2019-04-08 21:00:00
40798 2019-04-08 22:00:00
40799 2019-04-08 23:00:00

[40800 rows x 1 columns]

In [69]:
ts.datetime.dt.day_name()      #we will use the dt

0        Wednesday
1        Wednesday
2        Wednesday
3        Wednesday
4        Wednesday
           ...
40795       Monday
40796       Monday
40797       Monday
40798       Monday
40799       Monday
Name: datetime, Length: 40800, dtype: object

### creating the New data Frame based on the day time timestamps

In [75]:
lod_df.datetime.dt.day_name

In [76]:
ts['day']=lod_df.datetime.dt.day
ts['month']=lod_df.datetime.dt.month
ts['year']=lod_df.datetime.dt.year
ts['day_name']=lod_df.datetime.dt.day_name()
ts['month_name']=lod_df.datetime.dt.month_name()
ts['day_of_week']=lod_df.datetime.dt.day_of_week
ts['day_of_year']=lod_df.datetime.dt.day_of_year
ts['quarter']=lod_df.datetime.dt.quarter
ts['is_leap_year']=lod_df.datetime.dt.is_leap_year
ts['freq']=lod_df.datetime.dt.freq
# There are many more funtion to extract the info of date time coluim

In [77]:
ts

,datetime,day,month,year,day_name,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
0,2019-03-06 00:00:00,6,3,2019,Wednesday,March,2,65,1,False,None
1,2019-03-06 01:00:00,6,3,2019,Wednesday,March,2,65,1,False,None
2,2019-03-06 02:00:00,6,3,2019,Wednesday,March,2,65,1,False,None
3,2019-03-06 03:00:00,6,3,2019,Wednesday,March,2,65,1,False,None
4,2019-03-06 04:00:00,6,3,2019,Wednesday,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...
40795,2019-04-08 19:00:00,8,4,2019,Monday,April,0,98,2,False,None
40796,2019-04-08 20:00:00,8,4,2019,Monday,April,0,98,2,False,None
40797,2019-04-08 21:00:00,8,4,2019,Monday,April,0,98,2,False,None
40798,2019-04-08 22:00:00,8,4,2019,Monday,April,0,98,2,False,None
40799,2019-04-08 23:00:00,8,4,2019,Monday,April,0,98,2,False,None

## Creating a date that looks in dd-mm-yyyy format

In [103]:
x=ts[['day','month','year']]
x

       day  month  year
0        6      3  2019
1        6      3  2019
2        6      3  2019
3        6      3  2019
4        6      3  2019
...    ...    ...   ...
40795    8      4  2019
40796    8      4  2019
40797    8      4  2019
40798    8      4  2019
40799    8      4  2019

[40800 rows x 3 columns]

In [123]:
date1=pd.to_datetime(x,format=('%d-%m-%Y'))
date1
ts.insert(loc=5,column='yyyy-mm-dd',value=date1)

0       2019-03-06
1       2019-03-06
2       2019-03-06
3       2019-03-06
4       2019-03-06
           ...
40795   2019-04-08
40796   2019-04-08
40797   2019-04-08
40798   2019-04-08
40799   2019-04-08
Length: 40800, dtype: datetime64[ns]

In [124]:
ts

,datetime,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
0,2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
1,2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2,2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
3,2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
4,2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40795,2019-04-08 19:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40796,2019-04-08 20:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40797,2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40798,2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40799,2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None

### `to_period`
- is a Pandas function used to convert dates or date-like values into a Period object (representing a span of time rather than a specific timestamp).

In [79]:
lod_df.datetime.dt.to_period('Q') # HERE Q id-s frequency

0        2019Q1
1        2019Q1
2        2019Q1
3        2019Q1
4        2019Q1
          ...
40795    2019Q2
40796    2019Q2
40797    2019Q2
40798    2019Q2
40799    2019Q2
Name: datetime, Length: 40800, dtype: period[Q-DEC]

## `freq `
- parameter inside .to_period(freq) tells what time span (granularity) the period should represent.

| Freq Code | Description                          | Example Output (for 2024-09-02) |
|-----------|--------------------------------------|---------------------------------|
| D         | Daily                                | 2024-09-02                      |
| W         | Weekly (ends on Sunday by default)   | 2024-08-26/2024-09-01           |
| M         | Month End                            | 2024-09                         |
| MS        | Month Start                          | 2024-09                         |
| Q         | Quarter End (default: Dec year-end)  | 2024Q3                          |
| Q-DEC     | Quarter ending in December           | 2024Q3                          |
| Q-MAR     | Quarter ending in March              | 2024Q2                          |
| A or Y    | Year End (default: Dec)              | 2024                            |
| AS        | Year Start                           | 2024                            |
| H         | Hourly                               | 2024-09-02 00:00                |
| T or min  | Minutely                             | 2024-09-02 00:00                |
| S         | Secondly                             | 2024-09-02 00:00:00             |

In [127]:
ts.datetime.dt.to_period('M')

0        2019-03
1        2019-03
2        2019-03
3        2019-03
4        2019-03
          ...
40795    2019-04
40796    2019-04
40797    2019-04
40798    2019-04
40799    2019-04
Name: datetime, Length: 40800, dtype: period[M]

## Benifits of date being index

In [128]:
ts.set_index('datetime',inplace=True)

In [129]:
ts

,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
datetime,,,,,,,,,,,,
2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-08 19:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 20:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None

#### -> We can easyly access the rows by iloc by giving the ranges

In [133]:
# b/w days
ts.loc[2019-03-06:2019-03-12] # we cannot dccess by date dtype

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (1869297691.py, line 2)

### We can access the elements by using valid slicing or indexing

In [137]:
ts.loc['2019-03-06'] # All the rows from all hours at date

,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
datetime,,,,,,,,,,,,
2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-06 19:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 20:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 21:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 22:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 23:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None

In [145]:
ts.at_time('23:00:00')
ts.between_time(start_time='21:00:00',end_time='23:00:00')

,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
datetime,,,,,,,,,,,,
2019-03-06 23:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-07 23:00:00,7,3,2019,Thursday,2019-03-07,HI,March,3,66,1,False,None
2019-03-08 23:00:00,8,3,2019,Friday,2019-03-08,HI,March,4,67,1,False,None
2019-03-09 23:00:00,9,3,2019,Saturday,2019-03-09,HI,March,5,68,1,False,None
2019-03-10 23:00:00,10,3,2019,Sunday,2019-03-10,HI,March,6,69,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-04 23:00:00,4,4,2019,Thursday,2019-04-04,HI,April,3,94,2,False,None
2019-04-05 23:00:00,5,4,2019,Friday,2019-04-05,HI,April,4,95,2,False,None
2019-04-06 23:00:00,6,4,2019,Saturday,2019-04-06,HI,April,5,96,2,False,None
2019-04-07 23:00:00,7,4,2019,Sunday,2019-04-07,HI,April,6,97,2,False,None
2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None

,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
datetime,,,,,,,,,,,,
2019-03-06 21:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 22:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-06 23:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2019-03-07 21:00:00,7,3,2019,Thursday,2019-03-07,HI,March,3,66,1,False,None
2019-03-07 22:00:00,7,3,2019,Thursday,2019-03-07,HI,March,3,66,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-07 22:00:00,7,4,2019,Sunday,2019-04-07,HI,April,6,97,2,False,None
2019-04-07 23:00:00,7,4,2019,Sunday,2019-04-07,HI,April,6,97,2,False,None
2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None

# We should convert datetime  into string

In [151]:
### strf
ts.reset_index(inplace=True)

In [154]:
ts

,datetime,day,month,year,day_name,yyyy-mm-dd,date1,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
0,2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
1,2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
2,2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
3,2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
4,2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,HI,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40795,2019-04-08 19:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40796,2019-04-08 20:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40797,2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40798,2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None
40799,2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,HI,April,0,98,2,False,None

In [158]:
strd=ts.datetime.dt.strftime('%d-%m-%Y')
ts['strd']=strd

In [160]:
strd.dtype  # Date is converted into object mean str

dtype('O')

In [166]:
ts.insert(6,column='String_Date',value=strd)

In [167]:
ts

,datetime,day,month,year,day_name,yyyy-mm-dd,String_Date,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
0,2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
1,2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
2,2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
3,2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
4,2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40795,2019-04-08 19:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40796,2019-04-08 20:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40797,2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40798,2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40799,2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None

# Time Delta

- timedelta lets you specify days, seconds, microseconds, milliseconds, minutes, hours, weeks.

- Add it to a datetime (Python) or Timestamp (Pandas) to create a new timestamp.

In [191]:
pd.Timedelta(days=5)

Timedelta('5 days 00:00:00')

In [192]:
pd.Timedelta(days=5,hours=8)

Timedelta('5 days 08:00:00')

In [195]:
pd.Timedelta(days=5,hours=8,seconds=55)

Timedelta('5 days 08:00:55')

### If yow want to add or subrate the existing timestamp columns use the time delta

In [196]:
ts

,datetime,day,month,year,day_name,yyyy-mm-dd,String_Date,month_name,day_of_week,day_of_year,quarter,is_leap_year,freq
0,2019-03-06 00:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
1,2019-03-06 01:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
2,2019-03-06 02:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
3,2019-03-06 03:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
4,2019-03-06 04:00:00,6,3,2019,Wednesday,2019-03-06,06-03-2019,March,2,65,1,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40795,2019-04-08 19:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40796,2019-04-08 20:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40797,2019-04-08 21:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40798,2019-04-08 22:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None
40799,2019-04-08 23:00:00,8,4,2019,Monday,2019-04-08,08-04-2019,April,0,98,2,False,None

## adding 5 days in march

In [209]:
print('Before Dataframe :')
ts.datetime

print('\n\n After Dataframe :')
(ts.datetime[ts.month_name=='March']+pd.Timedelta(days=1)).reset_index()

Before Dataframe :

0       2019-03-06 00:00:00
1       2019-03-06 01:00:00
2       2019-03-06 02:00:00
3       2019-03-06 03:00:00
4       2019-03-06 04:00:00
                ...
40795   2019-04-08 19:00:00
40796   2019-04-08 20:00:00
40797   2019-04-08 21:00:00
40798   2019-04-08 22:00:00
40799   2019-04-08 23:00:00
Name: datetime, Length: 40800, dtype: datetime64[ns]

 After Dataframe :

       index            datetime
0          0 2019-03-07 00:00:00
1          1 2019-03-07 01:00:00
2          2 2019-03-07 02:00:00
3          3 2019-03-07 03:00:00
4          4 2019-03-07 04:00:00
...      ...                 ...
31195  40603 2019-04-01 19:00:00
31196  40604 2019-04-01 20:00:00
31197  40605 2019-04-01 21:00:00
31198  40606 2019-04-01 22:00:00
31199  40607 2019-04-01 23:00:00

[31200 rows x 2 columns]

Indexes do not reset automatically after filtering.

The values are still correct, but the row numbers (indices) are carried over from the original DataFrame.

Example: If you drop some rows (like keeping only certain hours or applying a condition), the DataFrame keeps the original index unless you call reset_index().

# Date Range

### Pandas has a super useful function pd.date_range() for creating a sequence of datetimes.

### pd.date_range you can’t use periods and freq with both start and end at the same time.
Rules

If you use start + end + freq → Pandas figures out all the timestamps between them.

If you use start + periods + freq → Pandas generates n periods forward.

If you use end + periods + freq → Pandas generates n periods backward.

You cannot mix start, end, periods all together.

In [211]:
pd.date_range(start='2019-03-06', end='2019-03-12')

DatetimeIndex(['2019-03-06', '2019-03-07', '2019-03-08', '2019-03-09',
               '2019-03-10', '2019-03-11', '2019-03-12'],
              dtype='datetime64[ns]', freq='D')

In [212]:
pd.date_range(start='2019-03-06 00:00:00', end=' 2019-04-08 23:00:00')

DatetimeIndex(['2019-03-06', '2019-03-07', '2019-03-08', '2019-03-09',
               '2019-03-10', '2019-03-11', '2019-03-12', '2019-03-13',
               '2019-03-14', '2019-03-15', '2019-03-16', '2019-03-17',
               '2019-03-18', '2019-03-19', '2019-03-20', '2019-03-21',
               '2019-03-22', '2019-03-23', '2019-03-24', '2019-03-25',
               '2019-03-26', '2019-03-27', '2019-03-28', '2019-03-29',
               '2019-03-30', '2019-03-31', '2019-04-01', '2019-04-02',
               '2019-04-03', '2019-04-04', '2019-04-05', '2019-04-06',
               '2019-04-07', '2019-04-08'],
              dtype='datetime64[ns]', freq='D')

In [214]:
pd.date_range(start='2019-03-06 00:00:00', end=' 2019-04-08 23:00:00',periods=10) # it is like Bins automatecally shows only 10 values

DatetimeIndex(['2019-03-06 00:00:00', '2019-03-09 18:33:20',
               '2019-03-13 13:06:40', '2019-03-17 07:40:00',
               '2019-03-21 02:13:20', '2019-03-24 20:46:40',
               '2019-03-28 15:20:00', '2019-04-01 09:53:20',
               '2019-04-05 04:26:40', '2019-04-08 23:00:00'],
              dtype='datetime64[ns]', freq=None)

In [219]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='MS') #Month starting

DatetimeIndex(['2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01',
               '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01',
               '2019-12-01', '2020-01-01'],
              dtype='datetime64[ns]', freq='MS')

In [220]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='Q') #Quater

DatetimeIndex(['2019-03-31', '2019-06-30', '2019-09-30', '2019-12-31',
               '2020-03-31', '2020-06-30', '2020-09-30', '2020-12-31',
               '2021-03-31', '2021-06-30'],
              dtype='datetime64[ns]', freq='QE-DEC')

In [221]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='M') #monthend

DatetimeIndex(['2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30',
               '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31',
               '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [222]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='W') #weekly

DatetimeIndex(['2019-03-10', '2019-03-17', '2019-03-24', '2019-03-31',
               '2019-04-07', '2019-04-14', '2019-04-21', '2019-04-28',
               '2019-05-05', '2019-05-12'],
              dtype='datetime64[ns]', freq='W-SUN')

In [223]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='B') # Only Business days

DatetimeIndex(['2019-03-06', '2019-03-07', '2019-03-08', '2019-03-11',
               '2019-03-12', '2019-03-13', '2019-03-14', '2019-03-15',
               '2019-03-18', '2019-03-19'],
              dtype='datetime64[ns]', freq='B')

In [224]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='H') #hourly

DatetimeIndex(['2019-03-06 00:00:00', '2019-03-06 01:00:00',
               '2019-03-06 02:00:00', '2019-03-06 03:00:00',
               '2019-03-06 04:00:00', '2019-03-06 05:00:00',
               '2019-03-06 06:00:00', '2019-03-06 07:00:00',
               '2019-03-06 08:00:00', '2019-03-06 09:00:00'],
              dtype='datetime64[ns]', freq='h')

In [225]:
pd.date_range(start='2019-03-06 00:00:00',periods=10,freq='D ') #daily

DatetimeIndex(['2019-03-06', '2019-03-07', '2019-03-08', '2019-03-09',
               '2019-03-10', '2019-03-11', '2019-03-12', '2019-03-13',
               '2019-03-14', '2019-03-15'],
              dtype='datetime64[ns]', freq='D')