# Group By

### `groupby()` is a method used to split the data into groups based on one or more columns, and then apply aggregation or custom functions to each group.


#### - df.groupby([<categorical column(s)>])[[<numerical column(s)>]].agg_function() 
#### - df.groupby([<categorical column(s)>])[[<categorical column(s)>]].agg_function()

In [1]:
import pandas as pd
car_df=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\exported.xlsx")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [5]:
car_df.groupby('make') # returns the empty objects  without any operations

In [7]:
print(car_df.groupby('make')['price'])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x000001A970861160>

In [18]:
car_df.groupby('make')['price'].mean() #calculating the average prices of each

make
alfa-romero      15498.333333
audi             17859.166667
bmw              26118.750000
chevrolet         6007.000000
dodge             7875.444444
honda             8184.692308
isuzu             8916.500000
jaguar           34600.000000
mazda            10652.882353
mercedes-benz    33647.000000
mercury          16503.000000
mitsubishi        9239.769231
nissan           10415.666667
peugot           15489.090909
plymouth          7963.428571
porsche          31400.500000
renault           9595.000000
saab             15223.333333
subaru            8541.250000
toyota            9885.812500
volkswagen       10077.500000
volvo            18063.181818
Name: price, dtype: float64

In [22]:
#selecting the text values at right side 
car_df.groupby('body_style')['engine_location'].max()

body_style
convertible     rear
hardtop         rear
hatchback      front
sedan          front
wagon          front
Name: engine_location, dtype: object

In [23]:
#selecting the text values at right side 
car_df.groupby('body_style')['engine_location'].count()

body_style
convertible     6
hardtop         8
hatchback      70
sedan          96
wagon          25
Name: engine_location, dtype: int64

In [26]:
#giving the multiple indexes(Left Side )
car_df.groupby(['make','fuel_type'])[['price']].mean()

                                price
make          fuel_type
alfa-romero   gas        15498.333333
audi          gas        17859.166667
bmw           gas        26118.750000
chevrolet     gas         6007.000000
dodge         gas         7875.444444
honda         gas         8184.692308
isuzu         gas         8916.500000
jaguar        gas        34600.000000
mazda         diesel     14569.500000
              gas        10130.666667
mercedes-benz diesel     28394.000000
              gas        38900.000000
mercury       gas        16503.000000
mitsubishi    gas         9239.769231
nissan        diesel      7099.000000
              gas        10610.764706
peugot        diesel     15797.000000
              gas        15232.500000
plymouth      gas         7963.428571
porsche       gas        31400.500000
renault       gas         9595.000000
saab          gas        15223.333333
subaru        gas         8541.250000
toyota        diesel      8794.666667
              gas         9998.689655
volkswagen    diesel      9777.500000
              gas        10227.500000
volvo         diesel     22470.000000
              gas        17622.500000

In [28]:
car_df.groupby(['make','body_style'])[["city_mpg", "highway_mpg", "price"]].mean() #multiple colums at both index and value sides

                            city_mpg  highway_mpg         price
make          body_style
alfa-romero   convertible  21.000000    27.000000  14997.500000
              hatchback    19.000000    26.000000  16500.000000
audi          hatchback    16.000000    22.000000           NaN
              sedan        19.400000    24.400000  17647.000000
              wagon        19.000000    25.000000  18920.000000
bmw           sedan        19.375000    25.375000  26118.750000
chevrolet     hatchback    42.500000    48.000000   5723.000000
              sedan        38.000000    43.000000   6575.000000
dodge         hatchback    28.400000    34.200000   7819.800000
              sedan        28.666667    35.333333   7619.666667
              wagon        24.000000    30.000000   8921.000000
honda         hatchback    33.142857    38.285714   7054.428571
              sedan        26.600000    31.800000   9945.000000
              wagon        30.000000    34.000000   7295.000000
isuzu         hatchback    24.000000    29.000000  11048.000000
              sedan        33.333333    38.333333   6785.000000
jaguar        sedan        14.333333    18.333333  34600.000000
mazda         hatchback    23.700000    29.500000  10085.000000
              sedan        28.571429    35.428571  11464.142857
mercedes-benz convertible  16.000000    18.000000  35056.000000
              hardtop      18.000000    20.500000  36788.000000
              sedan        18.500000    21.000000  33074.000000
              wagon        22.000000    25.000000  28248.000000
mercury       hatchback    19.000000    24.000000  16503.000000
mitsubishi    hatchback    25.333333    31.222222   9597.888889
              sedan        24.000000    31.000000   8434.000000
nissan        hardtop      31.000000    37.000000   8249.000000
              hatchback    22.600000    28.800000  14409.000000
              sedan        29.222222    35.111111   8604.555556
              wagon        26.333333    32.000000   9915.666667
peugot        sedan        22.714286    27.857143  15758.571429
              wagon        22.000000    24.500000  15017.500000
plymouth      hatchback    27.750000    33.250000   8130.500000
              sedan        31.000000    38.000000   7150.500000
              wagon        24.000000    30.000000   8921.000000
porsche       convertible  17.000000    25.000000  37028.000000
              hardtop      17.000000    25.000000  33278.000000
              hatchback    18.000000    27.500000  22018.000000
renault       hatchback    23.000000    31.000000   9895.000000
              wagon        23.000000    31.000000   9295.000000
saab          hatchback    20.333333    27.333333  15013.333333
              sedan        20.333333    27.333333  15433.333333
subaru        hatchback    27.666667    32.666667   6591.333333
              sedan        26.800000    31.200000   9070.600000
              wagon        24.750000    28.750000   9342.000000
toyota        convertible  24.000000    30.000000  17669.000000
              hardtop      24.000000    30.000000   9762.333333
              hatchback    27.785714    33.428571   9616.000000
              sedan        29.100000    34.000000   9542.200000
              wagon        26.000000    31.250000   9836.000000
volkswagen    convertible  24.000000    29.000000  11595.000000
              hatchback    24.000000    29.000000   9980.000000
              sedan        30.000000    36.666667   9673.888889
              wagon        25.000000    31.000000  12290.000000
volvo         sedan        21.125000    25.750000  18726.875000
              wagon        21.333333    26.000000  16293.333333

In [33]:
# idf there is multiple column present at the indexes it will condider as the one tuple index so data type will be pandas series 
cards=car_df.groupby(['make','body_style'])["city_mpg"].mean() #multiple colums at both index and value sides
print(cards,'\n\n Type of cards is :',type(cards))

make           body_style
alfa-romero    convertible    21.000000
               hatchback      19.000000
audi           hatchback      16.000000
               sedan          19.400000
               wagon          19.000000
bmw            sedan          19.375000
chevrolet      hatchback      42.500000
               sedan          38.000000
dodge          hatchback      28.400000
               sedan          28.666667
               wagon          24.000000
honda          hatchback      33.142857
               sedan          26.600000
               wagon          30.000000
isuzu          hatchback      24.000000
               sedan          33.333333
jaguar         sedan          14.333333
mazda          hatchback      23.700000
               sedan          28.571429
mercedes-benz  convertible    16.000000
               hardtop        18.000000
               sedan          18.500000
               wagon          22.000000
mercury        hatchback      19.000000
mitsubishi     hatchback      25.333333
               sedan          24.000000
nissan         hardtop        31.000000
               hatchback      22.600000
               sedan          29.222222
               wagon          26.333333
peugot         sedan          22.714286
               wagon          22.000000
plymouth       hatchback      27.750000
               sedan          31.000000
               wagon          24.000000
porsche        convertible    17.000000
               hardtop        17.000000
               hatchback      18.000000
renault        hatchback      23.000000
               wagon          23.000000
saab           hatchback      20.333333
               sedan          20.333333
subaru         hatchback      27.666667
               sedan          26.800000
               wagon          24.750000
toyota         convertible    24.000000
               hardtop        24.000000
               hatchback      27.785714
               sedan          29.100000
               wagon          26.000000
volkswagen     convertible    24.000000
               hatchback      24.000000
               sedan          30.000000
               wagon          25.000000
volvo          sedan          21.125000
               wagon          21.333333
Name: city_mpg, dtype: float64

 Type of cards is : <class 'pandas.core.series.Series'>

In [35]:
#but if you give the values in the double brackets it will leads to pandas dataframe
cards=car_df.groupby(['make','body_style'])[["city_mpg"]].mean() #multiple colums at both index and value sides [[]] gives dataframe
print(cards,'\n\n Type of cards is :',type(cards))

                            city_mpg
make          body_style
alfa-romero   convertible  21.000000
              hatchback    19.000000
audi          hatchback    16.000000
              sedan        19.400000
              wagon        19.000000
bmw           sedan        19.375000
chevrolet     hatchback    42.500000
              sedan        38.000000
dodge         hatchback    28.400000
              sedan        28.666667
              wagon        24.000000
honda         hatchback    33.142857
              sedan        26.600000
              wagon        30.000000
isuzu         hatchback    24.000000
              sedan        33.333333
jaguar        sedan        14.333333
mazda         hatchback    23.700000
              sedan        28.571429
mercedes-benz convertible  16.000000
              hardtop      18.000000
              sedan        18.500000
              wagon        22.000000
mercury       hatchback    19.000000
mitsubishi    hatchback    25.333333
              sedan        24.000000
nissan        hardtop      31.000000
              hatchback    22.600000
              sedan        29.222222
              wagon        26.333333
peugot        sedan        22.714286
              wagon        22.000000
plymouth      hatchback    27.750000
              sedan        31.000000
              wagon        24.000000
porsche       convertible  17.000000
              hardtop      17.000000
              hatchback    18.000000
renault       hatchback    23.000000
              wagon        23.000000
saab          hatchback    20.333333
              sedan        20.333333
subaru        hatchback    27.666667
              sedan        26.800000
              wagon        24.750000
toyota        convertible  24.000000
              hardtop      24.000000
              hatchback    27.785714
              sedan        29.100000
              wagon        26.000000
volkswagen    convertible  24.000000
              hatchback    24.000000
              sedan        30.000000
              wagon        25.000000
volvo         sedan        21.125000
              wagon        21.333333

 Type of cards is : <class 'pandas.core.frame.DataFrame'>

In [62]:
#combining or appling the two diff aggrigate operations on singile cvolumn 
# min & max price by make
car_df.groupby('make')['price'].agg(min_price='min',max_price='max')

               min_price  max_price
make
alfa-romero      13495.0    16500.0
audi             13950.0    23875.0
bmw              16430.0    41315.0
chevrolet         5151.0     6575.0
dodge             5572.0    12964.0
honda             5399.0    12945.0
isuzu             6785.0    11048.0
jaguar           32250.0    36000.0
mazda             5195.0    18344.0
mercedes-benz    25552.0    45400.0
mercury          16503.0    16503.0
mitsubishi        5389.0    14869.0
nissan            5499.0    19699.0
peugot           11900.0    18150.0
plymouth          5572.0    12764.0
porsche          22018.0    37028.0
renault           9295.0     9895.0
saab             11850.0    18620.0
subaru            5118.0    11694.0
toyota            5348.0    17669.0
volkswagen        7775.0    13845.0
volvo            12940.0    22625.0

## Assignment

In [29]:
# Avg city_mpg by make
# Avg city_mp by num_of_doors 
# Avg price, highway_mpg by num_of_doors, engine_location 
# count of cars by engine_location, fuel_type 
# min & max price by make

In [36]:
# Avg city_mpg by make
car_df.groupby('make')[['city_mpg']].mean() #if you give the double brackets it will assumes as a pandas dataframe

                city_mpg
make
alfa-romero    20.333333
audi           18.857143
bmw            19.375000
chevrolet      41.000000
dodge          28.000000
honda          30.384615
isuzu          31.000000
jaguar         14.333333
mazda          25.705882
mercedes-benz  18.500000
mercury        19.000000
mitsubishi     24.923077
nissan         27.000000
peugot         22.454545
plymouth       28.142857
porsche        17.400000
renault        23.000000
saab           20.333333
subaru         26.333333
toyota         27.500000
volkswagen     28.583333
volvo          21.181818

In [40]:
# Avg city_mp by num_of_doors 
car_df.groupby('num_of_doors')[['city_mpg']].mean()

               city_mpg
num_of_doors
?             30.000000
four          25.052632
two           25.325843

In [44]:
# Avg price, highway_mpg by num_of_doors, engine_location 
car_df.groupby(['num_of_doors','engine_location'])[['price','highway_mpg']].mean()

                                     price  highway_mpg
num_of_doors engine_location
?            front             9676.500000    36.000000
four         front            13565.672566    30.429825
two          front            12033.433735    31.255814
             rear             34528.000000    25.000000

In [54]:
# count of cars by engine_location, fuel_type 
car_df.groupby('make')[['engine_location','fuel_type']].count()

               engine_location  fuel_type
make
alfa-romero                  3          3
audi                         7          7
bmw                          8          8
chevrolet                    3          3
dodge                        9          9
honda                       13         13
isuzu                        4          4
jaguar                       3          3
mazda                       17         17
mercedes-benz                8          8
mercury                      1          1
mitsubishi                  13         13
nissan                      18         18
peugot                      11         11
plymouth                     7          7
porsche                      5          5
renault                      2          2
saab                         6          6
subaru                      12         12
toyota                      32         32
volkswagen                  12         12
volvo                       11         11

In [61]:
# min & max price by make
car_df.groupby('make')['price'].agg(min_price='min',max_price='max').reset_index()

             make  min_price  max_price
0     alfa-romero    13495.0    16500.0
1            audi    13950.0    23875.0
2             bmw    16430.0    41315.0
3       chevrolet     5151.0     6575.0
4           dodge     5572.0    12964.0
5           honda     5399.0    12945.0
6           isuzu     6785.0    11048.0
7          jaguar    32250.0    36000.0
8           mazda     5195.0    18344.0
9   mercedes-benz    25552.0    45400.0
10        mercury    16503.0    16503.0
11     mitsubishi     5389.0    14869.0
12         nissan     5499.0    19699.0
13         peugot    11900.0    18150.0
14       plymouth     5572.0    12764.0
15        porsche    22018.0    37028.0
16        renault     9295.0     9895.0
17           saab    11850.0    18620.0
18         subaru     5118.0    11694.0
19         toyota     5348.0    17669.0
20     volkswagen     7775.0    13845.0
21          volvo    12940.0    22625.0

# as_index

* like when you aregrouped more than one column as index left side it will acts as a index inorder to restrict those behaviour we will use as indexm

In [66]:
carid=car_df.groupby(['make',	'fuel_type'])[['highway_mpg']].mean() #here ma
carid

                         highway_mpg
make          fuel_type
alfa-romero   gas          26.666667
audi          gas          24.142857
bmw           gas          25.375000
chevrolet     gas          46.333333
dodge         gas          34.111111
honda         gas          35.461538
isuzu         gas          36.000000
jaguar        gas          18.333333
mazda         diesel       40.500000
              gas          30.800000
mercedes-benz diesel       25.000000
              gas          17.000000
mercury       gas          24.000000
mitsubishi    gas          31.153846
nissan        diesel       50.000000
              gas          31.941176
peugot        diesel       29.800000
              gas          24.000000
plymouth      gas          34.142857
porsche       gas          26.000000
renault       gas          31.000000
saab          gas          27.333333
subaru        gas          30.750000
toyota        diesel       38.666667
              gas          32.310345
volkswagen    diesel       43.000000
              gas          30.875000
volvo         diesel       27.000000
              gas          25.700000

In [70]:
# above make	fuel_type	 acts as the index
carid.index #so multi index is there inorder to restrict
#             these act we use asindex

MultiIndex([(  'alfa-romero',    'gas'),
            (         'audi',    'gas'),
            (          'bmw',    'gas'),
            (    'chevrolet',    'gas'),
            (        'dodge',    'gas'),
            (        'honda',    'gas'),
            (        'isuzu',    'gas'),
            (       'jaguar',    'gas'),
            (        'mazda', 'diesel'),
            (        'mazda',    'gas'),
            ('mercedes-benz', 'diesel'),
            ('mercedes-benz',    'gas'),
            (      'mercury',    'gas'),
            (   'mitsubishi',    'gas'),
            (       'nissan', 'diesel'),
            (       'nissan',    'gas'),
            (       'peugot', 'diesel'),
            (       'peugot',    'gas'),
            (     'plymouth',    'gas'),
            (      'porsche',    'gas'),
            (      'renault',    'gas'),
            (         'saab',    'gas'),
            (       'subaru',    'gas'),
            (       'toyota', 'diesel'),
            (       'toyota',    'gas'),
            (   'volkswagen', 'diesel'),
            (   'volkswagen',    'gas'),
            (        'volvo', 'diesel'),
            (        'volvo',    'gas')],
           names=['make', 'fuel_type'])

In [73]:
car_df.groupby(['make',	'fuel_type'] ,as_index=False)[['highway_mpg']].mean()

             make fuel_type  highway_mpg
0     alfa-romero       gas    26.666667
1            audi       gas    24.142857
2             bmw       gas    25.375000
3       chevrolet       gas    46.333333
4           dodge       gas    34.111111
5           honda       gas    35.461538
6           isuzu       gas    36.000000
7          jaguar       gas    18.333333
8           mazda    diesel    40.500000
9           mazda       gas    30.800000
10  mercedes-benz    diesel    25.000000
11  mercedes-benz       gas    17.000000
12        mercury       gas    24.000000
13     mitsubishi       gas    31.153846
14         nissan    diesel    50.000000
15         nissan       gas    31.941176
16         peugot    diesel    29.800000
17         peugot       gas    24.000000
18       plymouth       gas    34.142857
19        porsche       gas    26.000000
20        renault       gas    31.000000
21           saab       gas    27.333333
22         subaru       gas    30.750000
23         toyota    diesel    38.666667
24         toyota       gas    32.310345
25     volkswagen    diesel    43.000000
26     volkswagen       gas    30.875000
27          volvo    diesel    27.000000
28          volvo       gas    25.700000

In [75]:
car_df.groupby(['make',	'fuel_type'] ,as_index=False)[['highway_mpg']].mean().index #so fixed the problem

RangeIndex(start=0, stop=29, step=1)

## Performing multiple aggrigate operations at same time

In [79]:
car_subdf=car_df.groupby(['make','body_style'] ,as_index=False)[['compression_ratio','highway_mpg','price']].mean()

In [80]:
car_subdf

             make   body_style  compression_ratio  highway_mpg         price
0     alfa-romero  convertible           9.000000    27.000000  14997.500000
1     alfa-romero    hatchback           9.000000    26.000000  16500.000000
2            audi    hatchback           7.000000    22.000000           NaN
3            audi        sedan           8.660000    24.400000  17647.000000
4            audi        wagon           8.500000    25.000000  18920.000000
5             bmw        sedan           8.575000    25.375000  26118.750000
6       chevrolet    hatchback           9.550000    48.000000   5723.000000
7       chevrolet        sedan           9.600000    43.000000   6575.000000
8           dodge    hatchback           8.562000    34.200000   7819.800000
9           dodge        sedan           8.800000    35.333333   7619.666667
10          dodge        wagon           8.500000    30.000000   8921.000000
11          honda    hatchback           9.328571    38.285714   7054.428571
12          honda        sedan           9.060000    31.800000   9945.000000
13          honda        wagon           9.200000    34.000000   7295.000000
14          isuzu    hatchback           9.200000    29.000000  11048.000000
15          isuzu        sedan           9.233333    38.333333   6785.000000
16         jaguar        sedan           9.233333    18.333333  34600.000000
17          mazda    hatchback           9.040000    29.500000  10085.000000
18          mazda        sedan          12.557143    35.428571  11464.142857
19  mercedes-benz  convertible           8.300000    18.000000  35056.000000
20  mercedes-benz      hardtop          14.750000    20.500000  36788.000000
21  mercedes-benz        sedan          14.825000    21.000000  33074.000000
22  mercedes-benz        wagon          21.500000    25.000000  28248.000000
23        mercury    hatchback           8.000000    24.000000  16503.000000
24     mitsubishi    hatchback           8.088889    31.222222   9597.888889
25     mitsubishi        sedan           8.000000    31.000000   8434.000000
26         nissan      hardtop           9.400000    37.000000   8249.000000
27         nissan    hatchback           8.740000    28.800000  14409.000000
28         nissan        sedan          10.600000    35.111111   8604.555556
29         nissan        wagon           9.266667    32.000000   9915.666667
30         peugot        sedan          13.600000    27.857143  15758.571429
31         peugot        wagon          14.700000    24.500000  15017.500000
32       plymouth    hatchback           8.350000    33.250000   8130.500000
33       plymouth        sedan           9.400000    38.000000   7150.500000
34       plymouth        wagon           8.500000    30.000000   8921.000000
35        porsche  convertible           9.500000    25.000000  37028.000000
36        porsche      hardtop           9.500000    25.000000  33278.000000
37        porsche    hatchback           9.750000    27.500000  22018.000000
38        renault    hatchback           8.700000    31.000000   9895.000000
39        renault        wagon           8.700000    31.000000   9295.000000
40           saab    hatchback           9.203333    27.333333  15013.333333
41           saab        sedan           9.200000    27.333333  15433.333333
42         subaru    hatchback           8.800000    32.666667   6591.333333
43         subaru        sedan           8.940000    31.200000   9070.600000
44         subaru        wagon           8.675000    28.750000   9342.000000
45         toyota  convertible           9.300000    30.000000  17669.000000
46         toyota      hardtop           9.300000    30.000000   9762.333333
47         toyota    hatchback          10.035714    33.428571   9616.000000
48         toyota        sedan          11.700000    34.000000   9542.200000
49         toyota        wagon           9.050000    31.250000   9836.000000
50     volkswagen  convertible           8.500000    29.000000  11595.000000
51     volkswagen    hatchback           8.500000    29.000000   9980.000000
52     volkswagen        sedan          15.277778    36.666667   9673.888889
53     volkswagen        wagon           9.000000    31.000000  12290.000000
54          volvo        sedan          10.750000    25.750000  18726.875000
55          volvo        wagon           8.833333    26.000000  16293.333333

In [83]:
# i want to applty multipile aggrigate funtions
car_df.groupby(['make','body_style'] ,as_index=False)\
    [['compression_ratio']].agg(['sum','mean'])

             make   body_style compression_ratio
                                             sum       mean
0     alfa-romero  convertible             18.00   9.000000
1     alfa-romero    hatchback              9.00   9.000000
2            audi    hatchback              7.00   7.000000
3            audi        sedan             43.30   8.660000
4            audi        wagon              8.50   8.500000
5             bmw        sedan             68.60   8.575000
6       chevrolet    hatchback             19.10   9.550000
7       chevrolet        sedan              9.60   9.600000
8           dodge    hatchback             42.81   8.562000
9           dodge        sedan             26.40   8.800000
10          dodge        wagon              8.50   8.500000
11          honda    hatchback             65.30   9.328571
12          honda        sedan             45.30   9.060000
13          honda        wagon              9.20   9.200000
14          isuzu    hatchback              9.20   9.200000
15          isuzu        sedan             27.70   9.233333
16         jaguar        sedan             27.70   9.233333
17          mazda    hatchback             90.40   9.040000
18          mazda        sedan             87.90  12.557143
19  mercedes-benz  convertible              8.30   8.300000
20  mercedes-benz      hardtop             29.50  14.750000
21  mercedes-benz        sedan             59.30  14.825000
22  mercedes-benz        wagon             21.50  21.500000
23        mercury    hatchback              8.00   8.000000
24     mitsubishi    hatchback             72.80   8.088889
25     mitsubishi        sedan             32.00   8.000000
26         nissan      hardtop              9.40   9.400000
27         nissan    hatchback             43.70   8.740000
28         nissan        sedan             95.40  10.600000
29         nissan        wagon             27.80   9.266667
30         peugot        sedan             95.20  13.600000
31         peugot        wagon             58.80  14.700000
32       plymouth    hatchback             33.40   8.350000
33       plymouth        sedan             18.80   9.400000
34       plymouth        wagon              8.50   8.500000
35        porsche  convertible              9.50   9.500000
36        porsche      hardtop             19.00   9.500000
37        porsche    hatchback             19.50   9.750000
38        renault    hatchback              8.70   8.700000
39        renault        wagon              8.70   8.700000
40           saab    hatchback             27.61   9.203333
41           saab        sedan             27.60   9.200000
42         subaru    hatchback             26.40   8.800000
43         subaru        sedan             44.70   8.940000
44         subaru        wagon             34.70   8.675000
45         toyota  convertible              9.30   9.300000
46         toyota      hardtop             27.90   9.300000
47         toyota    hatchback            140.50  10.035714
48         toyota        sedan            117.00  11.700000
49         toyota        wagon             36.20   9.050000
50     volkswagen  convertible              8.50   8.500000
51     volkswagen    hatchback              8.50   8.500000
52     volkswagen        sedan            137.50  15.277778
53     volkswagen        wagon              9.00   9.000000
54          volvo        sedan             86.00  10.750000
55          volvo        wagon             26.50   8.833333

In [84]:
#if i want to apply this on multiple colums ,we can it will prints more colums 
# i want to applty multipile aggrigate funtions
car_df.groupby(['make','body_style'] ,as_index=False)\
    [['compression_ratio','highway_mpg','price']].agg(['sum','mean'])

             make   body_style compression_ratio            highway_mpg  \
                                             sum       mean         sum
0     alfa-romero  convertible             18.00   9.000000          54
1     alfa-romero    hatchback              9.00   9.000000          26
2            audi    hatchback              7.00   7.000000          22
3            audi        sedan             43.30   8.660000         122
4            audi        wagon              8.50   8.500000          25
5             bmw        sedan             68.60   8.575000         203
6       chevrolet    hatchback             19.10   9.550000          96
7       chevrolet        sedan              9.60   9.600000          43
8           dodge    hatchback             42.81   8.562000         171
9           dodge        sedan             26.40   8.800000         106
10          dodge        wagon              8.50   8.500000          30
11          honda    hatchback             65.30   9.328571         268
12          honda        sedan             45.30   9.060000         159
13          honda        wagon              9.20   9.200000          34
14          isuzu    hatchback              9.20   9.200000          29
15          isuzu        sedan             27.70   9.233333         115
16         jaguar        sedan             27.70   9.233333          55
17          mazda    hatchback             90.40   9.040000         295
18          mazda        sedan             87.90  12.557143         248
19  mercedes-benz  convertible              8.30   8.300000          18
20  mercedes-benz      hardtop             29.50  14.750000          41
21  mercedes-benz        sedan             59.30  14.825000          84
22  mercedes-benz        wagon             21.50  21.500000          25
23        mercury    hatchback              8.00   8.000000          24
24     mitsubishi    hatchback             72.80   8.088889         281
25     mitsubishi        sedan             32.00   8.000000         124
26         nissan      hardtop              9.40   9.400000          37
27         nissan    hatchback             43.70   8.740000         144
28         nissan        sedan             95.40  10.600000         316
29         nissan        wagon             27.80   9.266667          96
30         peugot        sedan             95.20  13.600000         195
31         peugot        wagon             58.80  14.700000          98
32       plymouth    hatchback             33.40   8.350000         133
33       plymouth        sedan             18.80   9.400000          76
34       plymouth        wagon              8.50   8.500000          30
35        porsche  convertible              9.50   9.500000          25
36        porsche      hardtop             19.00   9.500000          50
37        porsche    hatchback             19.50   9.750000          55
38        renault    hatchback              8.70   8.700000          31
39        renault        wagon              8.70   8.700000          31
40           saab    hatchback             27.61   9.203333          82
41           saab        sedan             27.60   9.200000          82
42         subaru    hatchback             26.40   8.800000          98
43         subaru        sedan             44.70   8.940000         156
44         subaru        wagon             34.70   8.675000         115
45         toyota  convertible              9.30   9.300000          30
46         toyota      hardtop             27.90   9.300000          90
47         toyota    hatchback            140.50  10.035714         468
48         toyota        sedan            117.00  11.700000         340
49         toyota        wagon             36.20   9.050000         125
50     volkswagen  convertible              8.50   8.500000          29
51     volkswagen    hatchback              8.50   8.500000          29
52     volkswagen        sedan            137.50  15.277778         330
53     volkswagen        wagon              9.00   9.000000          31
54          volvo        sedan             86.00  10.750000         206
55          volvo        wagon             26.50   8.833333          78

                  price
         mean       sum          mean
0   27.000000   29995.0  14997.500000
1   26.000000   16500.0  16500.000000
2   22.000000       0.0           NaN
3   24.400000   88235.0  17647.000000
4   25.000000   18920.0  18920.000000
5   25.375000  208950.0  26118.750000
6   48.000000   11446.0   5723.000000
7   43.000000    6575.0   6575.000000
8   34.200000   39099.0   7819.800000
9   35.333333   22859.0   7619.666667
10  30.000000    8921.0   8921.000000
11  38.285714   49381.0   7054.428571
12  31.800000   49725.0   9945.000000
13  34.000000    7295.0   7295.000000
14  29.000000   11048.0  11048.000000
15  38.333333    6785.0   6785.000000
16  18.333333  103800.0  34600.000000
17  29.500000  100850.0  10085.000000
18  35.428571   80249.0  11464.142857
19  18.000000   35056.0  35056.000000
20  20.500000   73576.0  36788.000000
21  21.000000  132296.0  33074.000000
22  25.000000   28248.0  28248.000000
23  24.000000   16503.0  16503.000000
24  31.222222   86381.0   9597.888889
25  31.000000   33736.0   8434.000000
26  37.000000    8249.0   8249.000000
27  28.800000   72045.0  14409.000000
28  35.111111   77441.0   8604.555556
29  32.000000   29747.0   9915.666667
30  27.857143  110310.0  15758.571429
31  24.500000   60070.0  15017.500000
32  33.250000   32522.0   8130.500000
33  38.000000   14301.0   7150.500000
34  30.000000    8921.0   8921.000000
35  25.000000   37028.0  37028.000000
36  25.000000   66556.0  33278.000000
37  27.500000   22018.0  22018.000000
38  31.000000    9895.0   9895.000000
39  31.000000    9295.0   9295.000000
40  27.333333   45040.0  15013.333333
41  27.333333   46300.0  15433.333333
42  32.666667   19774.0   6591.333333
43  31.200000   45353.0   9070.600000
44  28.750000   37368.0   9342.000000
45  30.000000   17669.0  17669.000000
46  30.000000   29287.0   9762.333333
47  33.428571  134624.0   9616.000000
48  34.000000   95422.0   9542.200000
49  31.250000   39344.0   9836.000000
50  29.000000   11595.0  11595.000000
51  29.000000    9980.0   9980.000000
52  36.666667   87065.0   9673.888889
53  31.000000   12290.0  12290.000000
54  25.750000  149815.0  18726.875000
55  26.000000   48880.0  16293.333333

### can we perform aggrigate operations in text or non numeric or conceptual  columns
#### *Yes 👍 we can perform aggregation operations on text / non-numeric / categorical columns in pandas, but the available functions are different from numeric ones.

In [89]:
car_df.select_dtypes(exclude='number')

,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,engine_type,num_of_cylinders,fuel_system,horsepower,peak_rpm
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi,111,5000
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi,111,5000
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi,154,5000
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi,102,5500
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi,115,5500
...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi,114,5400
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi,160,5300
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi,134,5500
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi,106,4800
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi,114,5400

In [97]:
car_df.groupby(['make','body_style'] )[['num_of_cylinders']].agg(['count','max','min']).head(10)

                        num_of_cylinders
                                   count    max   min
make        body_style
alfa-romero convertible                2   four  four
            hatchback                  1    six   six
audi        hatchback                  1   five  five
            sedan                      5   four  five
            wagon                      1   five  five
bmw         sedan                      8    six  four
chevrolet   hatchback                  2  three  four
            sedan                      1   four  four
dodge       hatchback                  5   four  four
            sedan                      3   four  four

## Applying diffrent .agg funtions to diffrent types of individual  colums

*  can be done usin the dictionaries

In [115]:
car_df.groupby(['make','body_style'] )[['engine_type','num_of_cylinders','price']]\
    .agg({'engine_type':['count','max'],'num_of_cylinders':'count','price':'mean'}).

                          engine_type        num_of_cylinders         price
                                count    max            count          mean
make          body_style
alfa-romero   convertible           2   dohc                2  14997.500000
              hatchback             1   ohcv                1  16500.000000
audi          hatchback             1    ohc                1           NaN
              sedan                 5    ohc                5  17647.000000
              wagon                 1    ohc                1  18920.000000
bmw           sedan                 8    ohc                8  26118.750000
chevrolet     hatchback             2    ohc                2   5723.000000
              sedan                 1    ohc                1   6575.000000
dodge         hatchback             5    ohc                5   7819.800000
              sedan                 3    ohc                3   7619.666667
              wagon                 1    ohc                1   8921.000000
honda         hatchback             7    ohc                7   7054.428571
              sedan                 5    ohc                5   9945.000000
              wagon                 1    ohc                1   7295.000000
isuzu         hatchback             1    ohc                1  11048.000000
              sedan                 3    ohc                3   6785.000000
jaguar        sedan                 3   ohcv                3  34600.000000
mazda         hatchback            10  rotor               10  10085.000000
              sedan                 7    ohc                7  11464.142857
mercedes-benz convertible           1   ohcv                1  35056.000000
              hardtop               2   ohcv                2  36788.000000
              sedan                 4   ohcv                4  33074.000000
              wagon                 1    ohc                1  28248.000000
mercury       hatchback             1    ohc                1  16503.000000
mitsubishi    hatchback             9    ohc                9   9597.888889
              sedan                 4    ohc                4   8434.000000
nissan        hardtop               1    ohc                1   8249.000000
              hatchback             5   ohcv                5  14409.000000
              sedan                 9   ohcv                9   8604.555556
              wagon                 3   ohcv                3   9915.666667
peugot        sedan                 7      l                7  15758.571429
              wagon                 4      l                4  15017.500000
plymouth      hatchback             4    ohc                4   8130.500000
              sedan                 2    ohc                2   7150.500000
              wagon                 1    ohc                1   8921.000000
porsche       convertible           1   ohcf                1  37028.000000
              hardtop               2   ohcf                2  33278.000000
              hatchback             2    ohc                2  22018.000000
renault       hatchback             1    ohc                1   9895.000000
              wagon                 1    ohc                1   9295.000000
saab          hatchback             3    ohc                3  15013.333333
              sedan                 3    ohc                3  15433.333333
subaru        hatchback             3   ohcf                3   6591.333333
              sedan                 5   ohcf                5   9070.600000
              wagon                 4   ohcf                4   9342.000000
toyota        convertible           1    ohc                1  17669.000000
              hardtop               3    ohc                3   9762.333333
              hatchback            14    ohc               14   9616.000000
              sedan                10    ohc               10   9542.200000
              wagon                 4    ohc                4   9836.000000
volkswagen    convertible           1    ohc                1  11595.000000
              hatchback             1    ohc                1   9980.000000
              sedan                 9    ohc                9   9673.888889
              wagon                 1    ohc                1  12290.000000
volvo         sedan                 8   ohcv                8  18726.875000
              wagon                 3    ohc                3  16293.333333

In [2]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [6]:
type(car_df.groupby('aspiration')[['city_mpg']].sum())

pandas.core.frame.DataFrame