# slicing
### operations for getting colums and rows from table

In [3]:
import numpy as np
import pandas as pd

In [4]:
car_df=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\exported2.csv")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [5]:
#ways to extract the colums  are

print(car_df.make,end='\n\n') #extracting the single column as data series, it will only works if space b/w column label is not present
print(car_df['make'],end='\n\n') #extracting the single column as data series, it will works even if space b/w column label is present

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [6]:
print(car_df[['make']],end='\n\n')
print(type(car_df[['make']]))

            make
0    alfa-romero
1    alfa-romero
2    alfa-romero
3           audi
4           audi
..           ...
200        volvo
201        volvo
202        volvo
203        volvo
204        volvo

[205 rows x 1 columns]

<class 'pandas.core.frame.DataFrame'>

In [7]:
#accessing multiple columns 
car_df[['fuel_type','aspiration','num_of_doors','body_style']] # returns the table as dataframe bcoz multiple

    fuel_type aspiration num_of_doors   body_style
0         gas        std          two  convertible
1         gas        std          two  convertible
2         gas        std          two    hatchback
3         gas        std         four        sedan
4         gas        std         four        sedan
..        ...        ...          ...          ...
200       gas        std         four        sedan
201       gas      turbo         four        sedan
202       gas        std         four        sedan
203    diesel      turbo         four        sedan
204       gas      turbo         four        sedan

[205 rows x 4 columns]

In [8]:
# accessing one rows  
car_df[5:6][:]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250

In [9]:
# accessing multiple rows  columnabs
car_df[5:9][:]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875

In [10]:
# accessing multiple rows  limited columnabs
car_df[5:9][['make','fuel_type','body_style']]

   make fuel_type body_style
5  audi       gas      sedan
6  audi       gas      sedan
7  audi       gas      wagon
8  audi       gas      sedan

## Task: Get the below output: (make, count)
[('toyota', 32), ('nissan', 18), ('mazda', 17)]

In [11]:
lst=['toyota','nissan','mazda']
for i in range(car_df.make.nunique()):
    if(car_df['make'].value_counts().index[i] in lst):
        print(car_df.make.value_counts().index[i],int(car_df.make.value_counts().values[i]))

toyota 32
nissan 18
mazda 17

In [12]:
car_df.make.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

# loc:
* .loc[] → Label-based indexing
* You select data by the labels (names) of rows and columns.

* It includes the end index when slicing.

* Can take boolean conditions and label names.

In [13]:
car_df.loc[:] #all rows and colums

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [18]:
car_df.loc[0:5]  #getting the row indexes

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250

In [20]:
car_df.index=[f'row_{i}' for i in range(len(car_df))]
car_df.head()

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
row_0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
row_1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
row_2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
row_3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
row_4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450

In [21]:
car_df.loc['row_1':'row_8' ] #getting the row indexes by labels

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
row_1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
row_2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
row_3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
row_4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
row_5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
row_6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
row_7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
row_8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875

In [22]:
car_df.loc['row_1':'row_8' :2] #getting the row indexes by labels with step values

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
row_1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
row_3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
row_5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
row_7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920

In [23]:
car_df.loc['row_1':'row_8' ,['make','aspiration']] #getting the multiple rows and columns

              make aspiration
row_1  alfa-romero        std
row_2  alfa-romero        std
row_3         audi        std
row_4         audi        std
row_5         audi        std
row_6         audi        std
row_7         audi        std
row_8         audi      turbo

# .iloc[] → Position-based indexing
* You select data by the integer positions of rows and columns.

* It excludes the end index when slicing (like normal Python list slicing).

* Cannot directly take label names.

In [26]:
car_df=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\exported2.csv")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [33]:
car_df.iloc[::,::] # rows[start:end:step] colrows[start:end:step]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [34]:
car_df.iloc[1:5,::] #1-5 rows all columns

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450

In [37]:
car_df.iloc[0:6,0:3] #accessing 6rows ,3 columns

   Unnamed: 0         make fuel_type
0           1  alfa-romero       gas
1           2  alfa-romero       gas
2           3  alfa-romero       gas
3           4         audi       gas
4           5         audi       gas
5           6         audi       gas

In [39]:
car_df.iloc[0:8:2,::] #accessing rows with step values

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710

In [40]:
car_df.iloc[0:8:2,::4] #accssing rows and colums using step values

   Unnamed: 0 num_of_doors  wheel_base  curb_weight fuel_system  city_mpg
0           1          two        88.6         2548        mpfi        21
2           3          two        94.5         2823        mpfi        19
4           5         four        99.4         2824        mpfi        18
6           7         four       105.8         2844        mpfi        19

# Important!!!!!!!!!!!!!!!! **********

In [62]:
#if you are using loc [start:end] end is inclusive -->]
car_df.loc[0:2] # 10

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500

In [63]:
#if you are using iloc [start:end) end is ecclusive-->) 
car_df.iloc[0:2] # 10

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500

In [65]:
#normal indexing or slicing it is exlusive 
car_df[1:5]['make']

1    alfa-romero
2    alfa-romero
3           audi
4           audi
Name: make, dtype: object

In [66]:
#normal indexing accesing rows and columns
car_df[1:5][['make','wheel_base']]

          make  wheel_base
1  alfa-romero        88.6
2  alfa-romero        94.5
3         audi        99.8
4         audi        99.4

In [69]:
#loc indexing accesing rows and columns #accessing by label names
car_df.loc[1:5,['make','wheel_base']]

          make  wheel_base
1  alfa-romero        88.6
2  alfa-romero        94.5
3         audi        99.8
4         audi        99.4
5         audi        99.8

In [71]:
#loc indexing accesing rows and columns #accessing elements by indexing or positions 
car_df.iloc[1:5:1,0:5:2]

   Unnamed: 0 fuel_type num_of_doors
1           2       gas          two
2           3       gas          two
3           4       gas         four
4           5       gas         four

## Task: Get the column names with index numbers as pairs
Sample output: [(0, 'Unnamed: 0'), (1, 'make'), (2, 'fuel_type'), (3, 'aspiration') .....]

### Few more:
- select rows 7 through 14 and columns 20 to 22 from a DataFrame
- select rows 7 through 14 and only the last column from a DataFrame
- select rows 7 through 14 and the last three columns from a DataFrame
- select the 7th row from the bottom of a DataFrame, along with its last three columns
- reverse the order of all rows in a DataFrame while keeping the columns in their original order
- reverse both the rows and the columns of a DataFrame

In [54]:
ind=car_df.index
val=car_df.columns
lst=[]
for i,every in zip(ind,val):
    lst.append((i,every))
lst

[(0, 'Unnamed: 0'),
 (1, 'make'),
 (2, 'fuel_type'),
 (3, 'aspiration'),
 (4, 'num_of_doors'),
 (5, 'body_style'),
 (6, 'drive_wheels'),
 (7, 'engine_location'),
 (8, 'wheel_base'),
 (9, 'length'),
 (10, 'width'),
 (11, 'height'),
 (12, 'curb_weight'),
 (13, 'engine_type'),
 (14, 'num_of_cylinders'),
 (15, 'engine_size'),
 (16, 'fuel_system'),
 (17, 'compression_ratio'),
 (18, 'horsepower'),
 (19, 'peak_rpm'),
 (20, 'city_mpg'),
 (21, 'highway_mpg'),
 (22, 'price')]


# Condition based Indexing

In [76]:
#extracting the data by using the specic condintions
car_df[car_df.make=='audi'] #gives the data that manufacture is audi

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?

### how the condition based indexing works

In [77]:
car_df.make=='audi'  #generates the  masked data, boolen data for any row

0      False
1      False
2      False
3       True
4       True
       ...
200    False
201    False
202    False
203    False
204    False
Name: make, Length: 205, dtype: bool

In [79]:
audi_cars=car_df[car_df.make=='audi'] #if you are appling the masked data return value[true/false] into data
                            #it will acts as the filter and returns the the only true values
audi_cars

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?

# multiple conditions

In [86]:
car_df[(car_df.make=='audi') & (car_df.body_style=='sedan') ] #using the and operation

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875

In [87]:
car_df[(car_df.make=='audi') & (car_df.wheel_base>100) ] #using the and operation

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875

In [89]:
car_df[(car_df.make=='audi') | (car_df.body_style=='wagon') ] #using the ORRR operation

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?
28,29,dodge,gas,std,four,wagon,fwd,front,103.3,174.6,...,ohc,four,122,2bbl,8.5,88,5000,24,30,8921
36,37,honda,gas,std,four,wagon,fwd,front,96.5,157.1,...,ohc,four,92,1bbl,9.2,76,6000,30,34,7295
68,69,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110.0,190.9,...,ohc,five,183,idi,21.5,123,4350,22,25,28248
93,94,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,...,ohc,four,97,2bbl,9.4,69,5200,31,37,7349
97,98,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,...,ohc,four,97,2bbl,9.4,69,5200,31,37,7999
102,103,nissan,gas,std,four,wagon,fwd,front,100.4,184.6,...,ohcv,six,181,mpfi,9.0,152,5200,17,22,14399
109,110,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,...,l,four,120,mpfi,8.4,97,5000,19,24,12440
110,111,peugot,diesel,turbo,four,wagon,rwd,front,114.2,198.9,...,l,four,152,idi,21.0,95,4150,25,25,13860
113,114,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,...,l,four,120,mpfi,8.4,95,5000,19,24,16695
114,115,peugot,diesel,turbo,four,wagon,rwd,front,114.2,198.9,...,l,four,152,idi,21.0,95,4150,25,25,17075
123,124,plymouth,gas,std,four,wagon,fwd,front,103.3,174.6,...,ohc,four,122,2bbl,8.5,88,5000,24,30,8921
130,131,renault,gas,std,four,wagon,fwd,front,96.1,181.5,...,ohc,four,132,mpfi,8.7,?,?,23,31,9295
146,147,subaru,gas,std,four,wagon,fwd,front,97.0,173.5,...,ohcf,four,108,2bbl,9.0,82,4800,28,32,7463
147,148,subaru,gas,std,four,wagon,fwd,front,97.0,173.5,...,ohcf,four,108,mpfi,9.0,94,5200,25,31,10198
148,149,subaru,gas,std,four,wagon,4wd,front,96.9,173.6,...,ohcf,four,108,2bbl,9.0,82,4800,23,29,8013
149,150,subaru,gas,turbo,four,wagon,4wd,front,96.9,173.6,...,ohcf,four,108,mpfi,7.7,111,4800,23,23,11694
153,154,toyota,gas,std,four,wagon,fwd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,31,37,6918
154,155,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,7898
155,156,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,8778
181,182,toyota,gas,std,four,wagon,rwd,front,104.5,187.8,...,dohc,six,161,mpfi,9.2,156,5200,19,24,15750
193,194,volkswagen,gas,std,four,wagon,fwd,front,100.4,183.1,...,ohc,four,109,mpfi,9.0,88,5500,25,31,12290
195,196,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,13415
197,198,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,16515
199,200,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18950

In [ ]:
# ToDo: 
# get all bmw cars with two doors 
# Extract all diesel sedan cars with highway milage more than 40
# Extract the cars audi or volvo  
# filter rows with wheel base more than 115 
# filter the turbo cars with 5 cylinders 
# filter the cars manufactured by Benz or Jaguar 
# filter the cars with two or four doors and sedan or hatchback and
    # wheel base more than 85 and with four or five cylinders

In [93]:
# get all bmw cars with two doors 
car_df[(car_df.make=='bmw') & (car_df.num_of_doors=='two')]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
10,11,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,...,ohc,four,108,mpfi,8.8,101,5800,23,29,16430
12,13,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,...,ohc,six,164,mpfi,9.0,121,4250,21,28,20970
16,17,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,...,ohc,six,209,mpfi,8.0,182,5400,16,22,41315

In [108]:
# Extract all diesel sedan cars with highway milage more than 40
car_df[((car_df.fuel_type=='diesel') &(car_df.body_style=='sedan')) & (car_df.highway_mpg>40)]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
63,64,mazda,diesel,std,?,sedan,fwd,front,98.8,177.8,...,ohc,four,122,idi,22.7,64,4650,36,42,10795
90,91,nissan,diesel,std,two,sedan,fwd,front,94.5,165.3,...,ohc,four,103,idi,21.9,55,4800,45,50,7099
182,183,volkswagen,diesel,std,two,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7775
184,185,volkswagen,diesel,std,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7995
187,188,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,68,4500,37,42,9495

In [96]:
# Extract the cars audi or volvo 
car_df[(car_df.make=='audi') | (car_df.make=='volvo')]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,8,audi,gas,std,four,wagon,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?
194,195,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,12940
195,196,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,13415
196,197,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,15985
197,198,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,16515
198,199,volvo,gas,turbo,four,sedan,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18420
199,200,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18950
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [97]:
# filter rows with wheel base more than 115 
car_df[car_df.wheel_base>115]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
70,71,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,202.6,...,ohc,five,183,idi,21.5,123,4350,22,25,31600
71,72,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,202.6,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,34184
73,74,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,208.1,...,ohcv,eight,308,mpfi,8.0,184,4500,14,16,40960

In [98]:
# filter the turbo cars with 5 cylinders
car_df[(car_df.aspiration=='turbo') & (car_df.num_of_cylinders=='five')]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?
67,68,mercedes-benz,diesel,turbo,four,sedan,rwd,front,110.0,190.9,...,ohc,five,183,idi,21.5,123,4350,22,25,25552
68,69,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110.0,190.9,...,ohc,five,183,idi,21.5,123,4350,22,25,28248
69,70,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,187.5,...,ohc,five,183,idi,21.5,123,4350,22,25,28176
70,71,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,202.6,...,ohc,five,183,idi,21.5,123,4350,22,25,31600

In [104]:
# filter the cars manufactured by Benz or Jaguar 
car_df[(car_df.make=='mercedes-benz') | (car_df.make=='jaguar')]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
47,48,jaguar,gas,std,four,sedan,rwd,front,113.0,199.6,...,dohc,six,258,mpfi,8.1,176,4750,15,19,32250
48,49,jaguar,gas,std,four,sedan,rwd,front,113.0,199.6,...,dohc,six,258,mpfi,8.1,176,4750,15,19,35550
49,50,jaguar,gas,std,two,sedan,rwd,front,102.0,191.7,...,ohcv,twelve,326,mpfi,11.5,262,5000,13,17,36000
67,68,mercedes-benz,diesel,turbo,four,sedan,rwd,front,110.0,190.9,...,ohc,five,183,idi,21.5,123,4350,22,25,25552
68,69,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110.0,190.9,...,ohc,five,183,idi,21.5,123,4350,22,25,28248
69,70,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,187.5,...,ohc,five,183,idi,21.5,123,4350,22,25,28176
70,71,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,202.6,...,ohc,five,183,idi,21.5,123,4350,22,25,31600
71,72,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,202.6,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,34184
72,73,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,180.3,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,35056
73,74,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,208.1,...,ohcv,eight,308,mpfi,8.0,184,4500,14,16,40960
74,75,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,199.2,...,ohcv,eight,304,mpfi,8.0,184,4500,14,16,45400

In [114]:
# filter the cars with two or four doors and sedan or hatchback and
    # wheel base more than 85 and with four or five cylinders 
car_df[((car_df.num_of_doors=='two')|(car_df.num_of_doors=='four'))&((car_df.body_style=='sedan')|(car_df.body_style=='hatchback'))& (car_df.wheel_base>40)&((car_df.num_of_cylinders=='four') |(car_df.num_of_cylinders=='five'))]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,6,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,7,audi,gas,std,four,sedan,fwd,front,105.8,192.7,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
8,9,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,197,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,15985
198,199,volvo,gas,turbo,four,sedan,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18420
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [103]:
car_df.loc[10:50]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
10,11,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,...,ohc,four,108,mpfi,8.80,101,5800,23,29,16430
11,12,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,...,ohc,four,108,mpfi,8.80,101,5800,23,29,16925
12,13,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,...,ohc,six,164,mpfi,9.00,121,4250,21,28,20970
13,14,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,...,ohc,six,164,mpfi,9.00,121,4250,21,28,21105
14,15,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,...,ohc,six,164,mpfi,9.00,121,4250,20,25,24565
15,16,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,...,ohc,six,209,mpfi,8.00,182,5400,16,22,30760
16,17,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,...,ohc,six,209,mpfi,8.00,182,5400,16,22,41315
17,18,bmw,gas,std,four,sedan,rwd,front,110.0,197.0,...,ohc,six,209,mpfi,8.00,182,5400,15,20,36880
18,19,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,...,l,three,61,2bbl,9.50,48,5100,47,53,5151
19,20,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,...,ohc,four,90,2bbl,9.60,70,5400,38,43,6295
20,21,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,...,ohc,four,90,2bbl,9.60,70,5400,38,43,6575
21,22,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,...,ohc,four,90,2bbl,9.41,68,5500,37,41,5572
22,23,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,...,ohc,four,90,2bbl,9.40,68,5500,31,38,6377
23,24,dodge,gas,turbo,two,hatchback,fwd,front,93.7,157.3,...,ohc,four,98,mpfi,7.60,102,5500,24,30,7957
24,25,dodge,gas,std,four,hatchback,fwd,front,93.7,157.3,...,ohc,four,90,2bbl,9.40,68,5500,31,38,6229
25,26,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,...,ohc,four,90,2bbl,9.40,68,5500,31,38,6692
26,27,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,...,ohc,four,90,2bbl,9.40,68,5500,31,38,7609
27,28,dodge,gas,turbo,?,sedan,fwd,front,93.7,157.3,...,ohc,four,98,mpfi,7.60,102,5500,24,30,8558
28,29,dodge,gas,std,four,wagon,fwd,front,103.3,174.6,...,ohc,four,122,2bbl,8.50,88,5000,24,30,8921
29,30,dodge,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,mfi,7.00,145,5000,19,24,12964
30,31,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,...,ohc,four,92,1bbl,9.60,58,4800,49,54,6479
31,32,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,...,ohc,four,92,1bbl,9.20,76,6000,31,38,6855
32,33,honda,gas,std,two,hatchback,fwd,front,93.7,150.0,...,ohc,four,79,1bbl,10.10,60,5500,38,42,5399
33,34,honda,gas,std,two,hatchback,fwd,front,93.7,150.0,...,ohc,four,92,1bbl,9.20,76,6000,30,34,6529
34,35,honda,gas,std,two,hatchback,fwd,front,93.7,150.0,...,ohc,four,92,1bbl,9.20,76,6000,30,34,7129
35,36,honda,gas,std,four,sedan,fwd,front,96.5,163.4,...,ohc,four,92,1bbl,9.20,76,6000,30,34,7295
36,37,honda,gas,std,four,wagon,fwd,front,96.5,157.1,...,ohc,four,92,1bbl,9.20,76,6000,30,34,7295
37,38,honda,gas,std,two,hatchback,fwd,front,96.5,167.5,...,ohc,four,110,1bbl,9.00,86,5800,27,33,7895
38,39,honda,gas,std,two,hatchback,fwd,front,96.5,167.5,...,ohc,four,110,1bbl,9.00,86,5800,27,33,9095
39,40,honda,gas,std,four,sedan,fwd,front,96.5,175.4,...,ohc,four,110,1bbl,9.00,86,5800,27,33,8845
40,41,honda,gas,std,four,sedan,fwd,front,96.5,175.4,...,ohc,four,110,1bbl,9.00,86,5800,27,33,10295
41,42,honda,gas,std,four,sedan,fwd,front,96.5,175.4,...,ohc,four,110,mpfi,9.00,101,5800,24,28,12945
42,43,honda,gas,std,two,sedan,fwd,front,96.5,169.1,...,ohc,four,110,2bbl,9.10,100,5500,25,31,10345
43,44,isuzu,gas,std,four,sedan,rwd,front,94.3,170.7,...,ohc,four,111,2bbl,8.50,78,4800,24,29,6785
44,45,isuzu,gas,std,two,sedan,fwd,front,94.5,155.9,...,ohc,four,90,2bbl,9.60,70,5400,38,43,?
45,46,isuzu,gas,std,four,sedan,fwd,front,94.5,155.9,...,ohc,four,90,2bbl,9.60,70,5400,38,43,?
46,47,isuzu,gas,std,two,hatchback,rwd,front,96.0,172.6,...,ohc,four,119,spfi,9.20,90,5000,24,29,11048
47,48,jaguar,gas,std,four,sedan,rwd,front,113.0,199.6,...,dohc,six,258,mpfi,8.10,176,4750,15,19,32250
48,49,jaguar,gas,std,four,sedan,rwd,front,113.0,199.6,...,dohc,six,258,mpfi,8.10,176,4750,15,19,35550
49,50,jaguar,gas,std,two,sedan,rwd,front,102.0,191.7,...,ohcv,twelve,326,mpfi,11.50,262,5000,13,17,36000
50,51,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.00,68,5000,30,31,5195

In [117]:
car_df.iloc[0]

Unnamed: 0                     1
make                 alfa-romero
fuel_type                    gas
aspiration                   std
num_of_doors                 two
body_style           convertible
drive_wheels                 rwd
engine_location            front
wheel_base                  88.6
length                     168.8
width                       64.1
height                      48.8
curb_weight                 2548
engine_type                 dohc
num_of_cylinders            four
engine_size                  130
fuel_system                 mpfi
compression_ratio            9.0
horsepower                   111
peak_rpm                    5000
city_mpg                      21
highway_mpg                   27
price                      13495
Name: 0, dtype: object