# Add a New & Derived Columns

In [76]:
import pandas as pd
import numpy as np
import random as rd
car_1df=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\car_data.xlsx",sheet_name='car')
car_df=car_1df.copy()

In [77]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [78]:
#adding the new column name 
# so use below 
car_df['manf_year']=1955 #applies the 1955 to all rows

In [79]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,manf_year
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,13495,1955
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,16500,1955
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,six,152,mpfi,9.0,154,5000,19,26,16500,1955
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,four,109,mpfi,10.0,102,5500,24,30,13950,1955
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,five,136,mpfi,8.0,115,5500,18,22,17450,1955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,23,28,16845,1955
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,8.7,160,5300,19,25,19045,1955
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,six,173,mpfi,8.8,134,5500,18,23,21485,1955
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,six,145,idi,23.0,106,4800,26,27,22470,1955
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,19,25,22625,1955

In [80]:
# tring with already exixting one s
car_df['manf_year']=1945

In [81]:
car_df #changeds the all values

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,manf_year
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,13495,1945
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,16500,1945
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,six,152,mpfi,9.0,154,5000,19,26,16500,1945
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,four,109,mpfi,10.0,102,5500,24,30,13950,1945
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,five,136,mpfi,8.0,115,5500,18,22,17450,1945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,23,28,16845,1945
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,8.7,160,5300,19,25,19045,1945
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,six,173,mpfi,8.8,134,5500,18,23,21485,1945
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,six,145,idi,23.0,106,4800,26,27,22470,1945
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,19,25,22625,1945

In [82]:
#changing the name of coliumn
car_df.rename(columns={'manf_year':'Year_of_Manufacture'},inplace=True)

In [83]:
car_df.rename(columns={'price':'price in $'},inplace=True)

In [84]:
car_df['Year_of_Manufacture']=np.random.randint(1945,2001,205)

In [91]:
# chaging the values of newly created column
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Price in rs,price in $,Year_of_Manufacture
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,0,13495,1996
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,0,16500,1986
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,9.0,154,5000,19,26,0,16500,1948
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,10.0,102,5500,24,30,0,13950,1977
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,8.0,115,5500,18,22,0,17450,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,23,28,0,16845,1976
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,8.7,160,5300,19,25,0,19045,1981
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,8.8,134,5500,18,23,0,21485,1947
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,23.0,106,4800,26,27,0,22470,1982
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,19,25,0,22625,1997

In [86]:
#inserting the column at choice position
car_df.insert(22,'Price in rs',0)

In [87]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Price in rs,price in $,Year_of_Manufacture
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,0,13495,1996
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,0,16500,1986
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,9.0,154,5000,19,26,0,16500,1948
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,10.0,102,5500,24,30,0,13950,1977
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,8.0,115,5500,18,22,0,17450,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,23,28,0,16845,1976
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,8.7,160,5300,19,25,0,19045,1981
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,8.8,134,5500,18,23,0,21485,1947
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,23.0,106,4800,26,27,0,22470,1982
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,19,25,0,22625,1997

In [88]:
# so we want convert the price in dollors to rupie
# we will have two approch

In [102]:
# traditional one 
lst=[]
tot=0
for every in car_df['price in $'].values:
    tot=every*87.50
    lst.append(tot)

In [103]:
car_df['Price in rs']=lst

In [104]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Price in rs,price in $,Year_of_Manufacture
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,1180812.5,13495,1996
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,9.0,111,5000,21,27,1443750.0,16500,1986
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,9.0,154,5000,19,26,1443750.0,16500,1948
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,10.0,102,5500,24,30,1220625.0,13950,1977
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,8.0,115,5500,18,22,1526875.0,17450,1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,23,28,1473937.5,16845,1976
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,8.7,160,5300,19,25,1666437.5,19045,1981
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,8.8,134,5500,18,23,1879937.5,21485,1947
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,23.0,106,4800,26,27,1966125.0,22470,1982
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,9.5,114,5400,19,25,1979687.5,22625,1997

# Mapping using the dictionaries

In [108]:
# So here colm num_of_doors represents the number but in text format 
# so inorder to convert them into numarics We use dict mapping
#it is possible only for the lower type of unique values in that column
#check the unique val of that one and work wit it 
car_df.num_of_doors.unique()

array(['two', 'four', '?'], dtype=object)

In [120]:
dictdoors={'two':2,'four':4,'?':0}

In [121]:
car_df.num_of_doors=car_df.num_of_doors.replace(dictdoors)

In [128]:
car_df.num_of_doors=car_df.num_of_doors.astype(int)

In [130]:
car_df.num_of_doors # so all values are ints with no null or duplicate value

0      2
1      2
2      2
3      4
4      4
      ..
200    4
201    4
202    4
203    4
204    4
Name: num_of_doors, Length: 205, dtype: int64

# Applying the funtions (Mapping using Funtions)

In [105]:
#or avery easy method is applying the funtions
#suppose a we want to add a catefgory to know which car is belongs to that one so we use funtions
#use apply keyword to applying the funtoon

def detect_cat(var):
    if(var<=10_000):
        return 'Affordable'
    elif(var>10_000 and var<=15_000):
        return 'Economy'
    else:
        return 'luxary'
detect_cat(1000000

'luxary'

In [106]:
#creating the new column catogry and appling these methons
car_df['categories']=car_df['price in $'].apply(detect_cat)

In [107]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Price in rs,price in $,Year_of_Manufacture,categories
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,mpfi,9.0,111,5000,21,27,1180812.5,13495,1996,Economy
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,mpfi,9.0,111,5000,21,27,1443750.0,16500,1986,luxary
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,mpfi,9.0,154,5000,19,26,1443750.0,16500,1948,luxary
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,mpfi,10.0,102,5500,24,30,1220625.0,13950,1977,Economy
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,mpfi,8.0,115,5500,18,22,1526875.0,17450,1984,luxary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,mpfi,9.5,114,5400,23,28,1473937.5,16845,1976,luxary
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,mpfi,8.7,160,5300,19,25,1666437.5,19045,1981,luxary
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,mpfi,8.8,134,5500,18,23,1879937.5,21485,1947,luxary
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,idi,23.0,106,4800,26,27,1966125.0,22470,1982,luxary
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,mpfi,9.5,114,5400,19,25,1979687.5,22625,1997,luxary

## using inline(Lambda Funtions)

In [141]:
# you want a column with the discounted price with lambda funtion 
#so discounted percentage is 10%
car_df['discounted_price$']=car_df['price in $'].apply((lambda x:x-x*(15/100)))

In [142]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Price in rs,price in $,Year_of_Manufacture,categories,discounted_price$
0,1,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,9.0,111,5000,21,27,1180812.5,13495,1996,Economy,11470.75
1,2,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,9.0,111,5000,21,27,1443750.0,16500,1986,luxary,14025.00
2,3,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,171.2,...,9.0,154,5000,19,26,1443750.0,16500,1948,luxary,14025.00
3,4,audi,gas,std,4,sedan,fwd,front,99.8,176.6,...,10.0,102,5500,24,30,1220625.0,13950,1977,Economy,11857.50
4,5,audi,gas,std,4,sedan,4wd,front,99.4,176.6,...,8.0,115,5500,18,22,1526875.0,17450,1984,luxary,14832.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,9.5,114,5400,23,28,1473937.5,16845,1976,luxary,14318.25
201,202,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,8.7,160,5300,19,25,1666437.5,19045,1981,luxary,16188.25
202,203,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,8.8,134,5500,18,23,1879937.5,21485,1947,luxary,18262.25
203,204,volvo,diesel,turbo,4,sedan,rwd,front,109.1,188.8,...,23.0,106,4800,26,27,1966125.0,22470,1982,luxary,19099.50
204,205,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,9.5,114,5400,19,25,1979687.5,22625,1997,luxary,19231.25

In [140]:
(lambda x:x-x*(15/100))(100)

85.0