# Renaming the columns

In [2]:
#we can rename the column labels 
#we seen previsionly we can nem it bu giveing attribute while creation
import pandas as pd
import numpy as np
import random as rd

In [32]:
car_df=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\exported2.csv")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [ ]:
# renaming the column name involves three types of methods

car_df.rename(columns={'past colum':'current col',
                       'past colum':'current col',  })   #but it is for preview only not updates the orginal col

# Method 2
car_df=car_df.rename(columns={'past colum':'current col',
                       'past colum':'current col', })     #it will originally updates originalthe data frame 

or 

car_df.rename(columns={'past colum':'current col',
                       'past colum':'current col', }, inplace=True)

In [5]:
#inorder to protect the orginal DF it is good practced to save the backup
car_df_backup=car_df.copy()

In [6]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [17]:
#changing the column names
updated_col={'make':'Manufacturer','price':'Cost'}
car_df.rename(columns=updated_col,inplace=True)

In [18]:
car_df

,Unnamed: 0,Manufacturer,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,Cost
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [23]:
#renaming all the Column names
array=np.array([['Amit', 'Priya', 'Rahul', 'Sneha', 'Kiran'], 
               [25, 28, 22, 30, 27],
               ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore'],
               ['Male', 'Female', 'Male', 'Female', 'Male']]) 
table_arr=pd.DataFrame(data=array.T,columns=[1,2,3,4],index=['row 1','row 2','row 3','row 4','row 5']) #changed the row name
table_arr

           1   2          3       4
row 1   Amit  25      Delhi    Male
row 2  Priya  28     Mumbai  Female
row 3  Rahul  22  Hyderabad    Male
row 4  Sneha  30    Chennai  Female
row 5  Kiran  27  Bangalore    Male

In [26]:
#renaming
table_arr.columns=['name','age','city','gender']

In [27]:
table_arr

        name age       city  gender
row 1   Amit  25      Delhi    Male
row 2  Priya  28     Mumbai  Female
row 3  Rahul  22  Hyderabad    Male
row 4  Sneha  30    Chennai  Female
row 5  Kiran  27  Bangalore    Male

In [19]:
#roll backinng the columns

car_df=car_df_backup.copy()

In [20]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

## Drop -> deleting the rows and the columns

In [49]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
50,51,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,30,31,5195
51,52,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6095
52,53,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6795
53,54,mazda,gas,std,four,sedan,fwd,front,93.1,166.8,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [51]:
#inorder to protect the orginal DF it is good practice to save the backup
car_df_backup=car_df.copy()

In [52]:
#dropping the rows
#if you want drop rows use the axis=0 for columns axis=1
car_df.drop(range(1,50),axis=0,inplace=True) #dropped the first 50 rows
                                             #inplace is must here also

In [54]:
# check the shape of the DF after drop() 
print(car_df.shape)
print(car_df_backup.shape)

(156, 23)
(205, 23)

In [36]:
# if you want to drop the columns use the axis is 1
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
50,51,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,30,31,5195
51,52,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6095
52,53,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6795
53,54,mazda,gas,std,four,sedan,fwd,front,93.1,166.8,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [38]:
#dropping the columns 
drop_col=['num_of_doors',	'body_style',	'drive_wheels',	'engine_location',	'wheel_base']
car_df.drop(drop_col,axis=1,inplace=True)

In [39]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,length,width,height,curb_weight,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,168.8,64.1,48.8,2548,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
50,51,mazda,gas,std,159.1,64.2,54.1,1890,ohc,four,91,2bbl,9.0,68,5000,30,31,5195
51,52,mazda,gas,std,159.1,64.2,54.1,1900,ohc,four,91,2bbl,9.0,68,5000,31,38,6095
52,53,mazda,gas,std,159.1,64.2,54.1,1905,ohc,four,91,2bbl,9.0,68,5000,31,38,6795
53,54,mazda,gas,std,166.8,64.2,54.1,1945,ohc,four,91,2bbl,9.0,68,5000,31,38,6695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,188.8,68.9,55.5,2952,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,188.8,68.8,55.5,3049,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,188.8,68.9,55.5,3217,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,188.8,68.9,55.5,3062,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [59]:
#droping the colums using the index names
columns=[0,1,3,4]
car_df.drop(car_df.columns[columns],axis=1,inplace=True) # Deleted the columns by using the indexes

In [60]:
# check the shape of the DF after drop() 
print(car_df.shape)
print(car_df_backup.shape)

(156, 19)
(205, 23)

In [75]:
#roll bacing the original data frame
car_df=car_df_backup.copy()

In [76]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

## condition based row deletion from DF

In [77]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [78]:
car_df.price

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

In [79]:
# here dtype refering the object bocoz any non numeric value is present b/w them we know how to find it
car_df.price.unique()

array(['13495', '16500', '13950', '17450', '15250', '17710', '18920',
       '23875', '?', '16430', '16925', '20970', '21105', '24565', '30760',
       '41315', '36880', '5151', '6295', '6575', '5572', '6377', '7957',
       '6229', '6692', '7609', '8558', '8921', '12964', '6479', '6855',
       '5399', '6529', '7129', '7295', '7895', '9095', '8845', '10295',
       '12945', '10345', '6785', '11048', '32250', '35550', '36000',
       '5195', '6095', '6795', '6695', '7395', '10945', '11845', '13645',
       '15645', '8495', '10595', '10245', '10795', '11245', '18280',
       '18344', '25552', '28248', '28176', '31600', '34184', '35056',
       '40960', '45400', '16503', '5389', '6189', '6669', '7689', '9959',
       '8499', '12629', '14869', '14489', '6989', '8189', '9279', '5499',
       '7099', '6649', '6849', '7349', '7299', '7799', '7499', '7999',
       '8249', '8949', '9549', '13499', '14399', '17199', '19699',
       '18399', '11900', '13200', '12440', '13860', '15580', '16900',
       '16695', '17075', '16630', '17950', '18150', '12764', '22018',
       '32528', '34028', '37028', '9295', '9895', '11850', '12170',
       '15040', '15510', '18620', '5118', '7053', '7603', '7126', '7775',
       '9960', '9233', '11259', '7463', '10198', '8013', '11694', '5348',
       '6338', '6488', '6918', '7898', '8778', '6938', '7198', '7788',
       '7738', '8358', '9258', '8058', '8238', '9298', '9538', '8449',
       '9639', '9989', '11199', '11549', '17669', '8948', '10698', '9988',
       '10898', '11248', '16558', '15998', '15690', '15750', '7975',
       '7995', '8195', '9495', '9995', '11595', '9980', '13295', '13845',
       '12290', '12940', '13415', '15985', '16515', '18420', '18950',
       '16845', '19045', '21485', '22470', '22625'], dtype=object)

In [81]:
#  there fore ? present in the values so we will remove it
#we didnot know exact position of it we use the condition based indexing
idx=car_df[car_df.price=='?'].index
idx

Index([9, 44, 45, 129], dtype='int64')

In [93]:
# deleting is 
drop_rows=car_df[car_df.price=='?'].index.to_list()
car_df.drop(drop_rows,axis=0,inplace=True)

In [100]:
print(car_df.shape)
print(car_df_backup.shape)

(201, 23)
(205, 23)

In [101]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [ ]:
#But data type is not changed

## Changing the dataType of columns

In [102]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         201 non-null    int64
 1   make               201 non-null    object
 2   fuel_type          201 non-null    object
 3   aspiration         201 non-null    object
 4   num_of_doors       201 non-null    object
 5   body_style         201 non-null    object
 6   drive_wheels       201 non-null    object
 7   engine_location    201 non-null    object
 8   wheel_base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb_weight        201 non-null    int64
 13  engine_type        201 non-null    object
 14  num_of_cylinders   201 non-null    object
 15  engine_size        201 non-null    int64
 16  fuel_system        201 non-null    object
 17  compression_ratio  201 non-null    float64
 18  horsepower         201 non-null    object
 19  peak_rpm           201 non-null    object
 20  city_mpg           201 non-null    int64
 21  highway_mpg        201 non-null    int64
 22  price              201 non-null    object
dtypes: float64(5), int64(5), object(13)
memory usage: 37.7+ KB

## Two main steps to remember while changing the datatype of a column

* **Step 1:** Always make sure all the elements in the column can be converted to the new data type.  
  - Example: If the data type is `object` and values are numeric (like `"10"`, `"25"`, `"3.5"`), it is convertible to `int` or `float`.  
  - If the value inside the object is a non-numeric string (like `"abc"`), it is **not** convertible to `int` or `float` without handling it first.

* **Step 2:** `inplace` does not work here — we need to override the column name after conversion.  
  - Example:  
    ```python
    df["col_name"] = df["col_name"].astype(int)
    ```

In [109]:
car_df=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\exported2.csv")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [110]:
# Aim is to convert the price col that is obj to floaat

# step1 checking all values are undergoes anumeric

print(car_df.price.str.isnumeric())
print(car_df.price.str.isnumeric().unique()) #str is used to y all the string method to given data

0      True
1      True
2      True
3      True
4      True
       ...
200    True
201    True
202    True
203    True
204    True
Name: price, Length: 205, dtype: bool
[ True False]

In [113]:
# there are flase values are present we need to remove it
# access the false elements
print(car_df.price[car_df.price.str.isnumeric()==False])

9      ?
44     ?
45     ?
129    ?
Name: price, dtype: object

In [117]:
#extract those colums '
indexes=car_df.price[car_df.price.str.isnumeric()==False].index.tolist()
indexes

[9, 44, 45, 129]

In [118]:
# drop those columns
car_df.drop(indexes,axis=0,inplace=True)

In [120]:
car_df.shape  #dropped 4 rows out of 205

(201, 23)

In [125]:
# rechack any non numeric values are present or not
car_df.price.str.isnumeric().value_counts()  # all are True now we can easylyy convert this\

price
True    201
Name: count, dtype: int64

In [126]:
car_df.price=car_df.price.astype(float)

In [127]:
car_df.price.info()      #all are float elemens

<class 'pandas.core.series.Series'>
Index: 201 entries, 0 to 204
Series name: price
Non-Null Count  Dtype
--------------  -----
201 non-null    float64
dtypes: float64(1)
memory usage: 3.1 KB

In [128]:
#like About method we can esyly conver all rows
car_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         201 non-null    int64
 1   make               201 non-null    object
 2   fuel_type          201 non-null    object
 3   aspiration         201 non-null    object
 4   num_of_doors       201 non-null    object
 5   body_style         201 non-null    object
 6   drive_wheels       201 non-null    object
 7   engine_location    201 non-null    object
 8   wheel_base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb_weight        201 non-null    int64
 13  engine_type        201 non-null    object
 14  num_of_cylinders   201 non-null    object
 15  engine_size        201 non-null    int64
 16  fuel_system        201 non-null    object
 17  compression_ratio  201 non-null    float64
 18  horsepower         201 non-null    object
 19  peak_rpm           201 non-null    object
 20  city_mpg           201 non-null    int64
 21  highway_mpg        201 non-null    int64
 22  price              201 non-null    float64
dtypes: float64(6), int64(5), object(12)
memory usage: 37.7+ KB

In [33]:
car_df.horsepower.str.isnumeric().value_counts()

horsepower
True     203
False      2
Name: count, dtype: int64

In [34]:
car_df.horsepower=car_df.horsepower.astype(float)

ValueError: could not convert string to float: '?'

In [35]:
# Ignoring the errors 
### ignoring the error doesnot convert the original data type but prints the daata withou error 
car_df.horsepower=car_df.horsepower.astype(float,errors='ignore')

In [36]:
car_df.horsepower.info()

<class 'pandas.core.series.Series'>
RangeIndex: 205 entries, 0 to 204
Series name: horsepower
Non-Null Count  Dtype
--------------  -----
205 non-null    object
dtypes: object(1)
memory usage: 1.7+ KB

In [37]:
car_df.horsepower

0      111
1      111
2      154
3      102
4      115
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: object

In [ ]:
#inorder to forcefully convert the data type  even non numeric values are preseent use the '' to_numeric AND coerce ''

In [38]:
car_df.horsepower=pd.to_numeric(car_df.horsepower,errors='coerce')

In [39]:
car_df.horsepower #given dtype is float64 so we able to convert it int using as type

0      111.0
1      111.0
2      154.0
3      102.0
4      115.0
       ...
200    114.0
201    160.0
202    134.0
203    106.0
204    114.0
Name: horsepower, Length: 205, dtype: float64

In [40]:
car_df.horsepower=car_df.horsepower.astype(int) #ERROR bcoz Nan values 
so we will remove the nana values

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

# Finding and filling NaN values in Pandas

In [41]:
# here they are converted into numericonce --> 
#what happens to '?' as numeric converted it as nan
#isna used to find whether NAN values are present or not
car_df[car_df.horsepower.isna()==True]

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
130,131,renault,gas,std,four,wagon,fwd,front,96.1,181.5,...,ohc,four,132,mpfi,8.7,NaN,?,23,31,9295
131,132,renault,gas,std,two,hatchback,fwd,front,96.1,176.8,...,ohc,four,132,mpfi,8.7,NaN,?,23,31,9895

In [42]:
#filling with random values
car_df.horsepower=car_df.horsepower.fillna(125)

In [43]:
#re-check nan values present or not
car_df.horsepower.isna().unique() #false that menan no nan value s

array([False])

In [44]:
car_df[car_df.horsepower.isna()==True]

Empty DataFrame
Columns: [Unnamed: 0, make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 23 columns]

In [45]:
### Now convert into int it will easyly converts bcoz we removed the nan value 
car_df.horsepower=car_df.horsepower.astype(int)

In [46]:
car_df.horsepower

0      111
1      111
2      154
3      102
4      115
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: int64

## Item assignment

In [58]:
# its very easy if you want to assign any values just accesst it through index and update it by hand
#makesure data type of assignment matches the old one 
car_df.loc[4:5,'horsepower']=25

In [59]:
car_df.horsepower

0      111
1      111
2      154
3      102
4       25
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: int64

# Adding the new Column

In [61]:
#if yount to add the new column 
#sytax is 
car_df['new']=1 #if new is present al valyues are replaces with 1
#or creates a new coloumn at the end

In [62]:
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,new
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,13495,1
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,9.0,111,5000,21,27,16500,1
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,six,152,mpfi,9.0,154,5000,19,26,16500,1
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,four,109,mpfi,10.0,102,5500,24,30,13950,1
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,five,136,mpfi,8.0,25,5500,18,22,17450,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,23,28,16845,1
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,8.7,160,5300,19,25,19045,1
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,six,173,mpfi,8.8,134,5500,18,23,21485,1
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,six,145,idi,23.0,106,4800,26,27,22470,1
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,four,141,mpfi,9.5,114,5400,19,25,22625,1