# Pandas

In [11]:
import pandas as pd
import numpy as np
import random as rd

In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
a = 10
b = 20
a + b

30

In [13]:
get_ipython()

In [14]:
#basucal;y pandas are used to deal with the tabular data
# heare data is stored in form of rows and colums
# rows also called as observation and colums called as the varibles or attributes

In [15]:
# Every column here follows a homogeneous approach, meaning it does not allow different data types within the same column

## Creating the data from the dictionaries

In [16]:
dict1 = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Kiran'],
    'Age': [25, 28, 22, 30, 27],
    'City': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
  'Profession': ['Engineer', 'Doctor', 'Student', 'Designer', 'Teacher']
}

In [67]:
dict1

{'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Kiran'],
 'Age': [25, 28, 22, 30, 27],
 'City': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore'],
 'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
 'Profession': ['Engineer', 'Doctor', 'Student', 'Designer', 'Teacher']}

In [18]:
# now we are creating the table from it
Table1=pd.DataFrame(dict1) #converts the given dict data into the tabulatr format

In [19]:
Table1

    Name  Age       City  Gender Profession
0   Amit   25      Delhi    Male   Engineer
1  Priya   28     Mumbai  Female     Doctor
2  Rahul   22  Hyderabad    Male    Student
3  Sneha   30    Chennai  Female   Designer
4  Kiran   27  Bangalore    Male    Teacher

In [39]:
#  changing the index of the data 
# so 
# row      -> for rows we call as the index
#columns    -> we call dirct colums
Table1=pd.DataFrame(data=dict1,index=range(101,106))

In [40]:
Name= ['Amit', 'Priya', 'Rahul', 'Sneha', 'Kiran']
Age= [25, 28, 22, 30, 27]
City= ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore']
Gender= ['Male', 'Female', 'Male', 'Female', 'Male']

In [41]:
#Creating the dataFrame using the list 
table_lst=pd.DataFrame(Name)

In [42]:
table_lst   # working Fine

       0
0   Amit
1  Priya
2  Rahul
3  Sneha
4  Kiran

In [ ]:
table_lst2=pd.DataFrame(Name)

In [43]:
table_lst=pd.DataFrame([Name,Age,City,Gender]) # like each data willnot print  Inorder , 
table_lst

       0       1          2        3          4
0   Amit   Priya      Rahul    Sneha      Kiran
1     25      28         22       30         27
2  Delhi  Mumbai  Hyderabad  Chennai  Bangalore
3   Male  Female       Male   Female       Male

In [44]:
# to maintain order we use ZIP.........

In [45]:
#so to come in single  list in same column\
list(zip(Name,Age,City,Gender))

[('Amit', 25, 'Delhi', 'Male'),
 ('Priya', 28, 'Mumbai', 'Female'),
 ('Rahul', 22, 'Hyderabad', 'Male'),
 ('Sneha', 30, 'Chennai', 'Female'),
 ('Kiran', 27, 'Bangalore', 'Male')]

In [46]:
table_lst=pd.DataFrame(data=zip(Name,Age,City,Gender))
table_lst

       0   1          2       3
0   Amit  25      Delhi    Male
1  Priya  28     Mumbai  Female
2  Rahul  22  Hyderabad    Male
3  Sneha  30    Chennai  Female
4  Kiran  27  Bangalore    Male

## Creating the DataFrame using the Arrays

In [47]:
array=np.array([['Amit', 'Priya', 'Rahul', 'Sneha', 'Kiran'], 
               [25, 28, 22, 30, 27],
               ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore'],
               ['Male', 'Female', 'Male', 'Female', 'Male']])  # like given one is 2-D array
                                                              # it is a list inside list

In [48]:
#creating the table by using the array 
table_arr=pd.DataFrame(data=array)
table_arr # so it looks like inverted array # we will transpose the array

       0       1          2        3          4
0   Amit   Priya      Rahul    Sneha      Kiran
1     25      28         22       30         27
2  Delhi  Mumbai  Hyderabad  Chennai  Bangalore
3   Male  Female       Male   Female       Male

In [49]:
table_arr.T

       0   1          2       3
0   Amit  25      Delhi    Male
1  Priya  28     Mumbai  Female
2  Rahul  22  Hyderabad    Male
3  Sneha  30    Chennai  Female
4  Kiran  27  Bangalore    Male

# changing the colum_labels and Row labels

* `index` : it used to change the row name 
* `column` : it used to change the column name

In [50]:
table_arr=pd.DataFrame(data=array.T,columns=['Name','Age','city','gender']) #changed the column name
table_arr

    Name Age       city  gender
0   Amit  25      Delhi    Male
1  Priya  28     Mumbai  Female
2  Rahul  22  Hyderabad    Male
3  Sneha  30    Chennai  Female
4  Kiran  27  Bangalore    Male

In [51]:
table_arr=pd.DataFrame(data=array.T,columns=['Name','Age','city','gender'],index=range(1001,1006)) #changed the row name
table_arr

       Name Age       city  gender
1001   Amit  25      Delhi    Male
1002  Priya  28     Mumbai  Female
1003  Rahul  22  Hyderabad    Male
1004  Sneha  30    Chennai  Female
1005  Kiran  27  Bangalore    Male

In [52]:
# row labels and column lables will allows or acceps both string and int data type

In [53]:
table_arr=pd.DataFrame(data=array.T,columns=[1,2,3,4],index=['row 1','row 2','row 3','row 4','row 5']) #changed the row name
table_arr

           1   2          3       4
row 1   Amit  25      Delhi    Male
row 2  Priya  28     Mumbai  Female
row 3  Rahul  22  Hyderabad    Male
row 4  Sneha  30    Chennai  Female
row 5  Kiran  27  Bangalore    Male

## Properties of DataFrames

In [54]:
Table1

      Name  Age       City  Gender Profession
101   Amit   25      Delhi    Male   Engineer
102  Priya   28     Mumbai  Female     Doctor
103  Rahul   22  Hyderabad    Male    Student
104  Sneha   30    Chennai  Female   Designer
105  Kiran   27  Bangalore    Male    Teacher

In [55]:
print(" shape of table is :",Table1.shape)
print(" columns of table is :",Table1.columns)
print(" index of table is :",Table1.index)
print(" size of table is :",Table1.size)
print("\n dtypes of table is :",Table1.dtypes) #string is refered object in pandas 
print("\n length of table is :",len(Table1))

 shape of table is : (5, 5)
 columns of table is : Index(['Name', 'Age', 'City', 'Gender', 'Profession'], dtype='object')
 index of table is : RangeIndex(start=101, stop=106, step=1)
 size of table is : 25

 dtypes of table is : Name          object
Age            int64
City          object
Gender        object
Profession    object
dtype: object

 length of table is : 5

In [61]:
#few more properties 
print(" \nhead it will returns the first n terms of rows (by default n=5 or give n value )\n ",Table1.head(3)) #or we can give the numbers
print(" \ntail it will returns the last n terms of rows (by default n=5 or give n value )\n",Table1.tail(2))

head it will returns the first n terms of rows (by default n=5 or give n value )
        Name  Age       City  Gender Profession
101   Amit   25      Delhi    Male   Engineer
102  Priya   28     Mumbai  Female     Doctor
103  Rahul   22  Hyderabad    Male    Student

tail it will returns the last n terms of rows (by default n=5 or give n value )
       Name  Age       City  Gender Profession
104  Sneha   30    Chennai  Female   Designer
105  Kiran   27  Bangalore    Male    Teacher

In [56]:
#inorde rto give the comple info about table is 
Table1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 101 to 105
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   City        5 non-null      object
 3   Gender      5 non-null      object
 4   Profession  5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

In [63]:
Table1.values #returns the data values of each colum

array([['Amit', 25, 'Delhi', 'Male', 'Engineer'],
       ['Priya', 28, 'Mumbai', 'Female', 'Doctor'],
       ['Rahul', 22, 'Hyderabad', 'Male', 'Student'],
       ['Sneha', 30, 'Chennai', 'Female', 'Designer'],
       ['Kiran', 27, 'Bangalore', 'Male', 'Teacher']], dtype=object)

## changing the colum labels

In [64]:
Table1

      Name  Age       City  Gender Profession
101   Amit   25      Delhi    Male   Engineer
102  Priya   28     Mumbai  Female     Doctor
103  Rahul   22  Hyderabad    Male    Student
104  Sneha   30    Chennai  Female   Designer
105  Kiran   27  Bangalore    Male    Teacher

In [72]:
Table1.columns=['Student name', 'Age', 'City', 'Gender', 'Profession']

In [73]:
Table1

    Student name  Age       City  Gender Profession
101         Amit   25      Delhi    Male   Engineer
102        Priya   28     Mumbai  Female     Doctor
103        Rahul   22  Hyderabad    Male    Student
104        Sneha   30    Chennai  Female   Designer
105        Kiran   27  Bangalore    Male    Teacher

## Data Series 
- A Data Series is a one-dimensional (1-D) labeled array capable of holding any data type
- basically data series works with  is 1-D tabular data

In [97]:
#creating the onedimentional data

dict2={
    'Name': ['bejing', 'chigako','vishakapatnam']
}
data_series=pd.Series(dict2['Name'])
data_series

0           bejing
1          chigako
2    vishakapatnam
dtype: object

In [87]:
#creating series by list
list1=['bejing', 'chigako','vishakapatnam']
ds_2=pd.Series(list1,index=range(101,104))
ds_2

101           bejing
102          chigako
103    vishakapatnam
dtype: object

In [88]:
#creating series by arrays
arr1=np.array(['bejing', 'chigako','vishakapatnam'])
ds_2=pd.Series(arr1)
ds_2

0           bejing
1          chigako
2    vishakapatnam
dtype: object

In [99]:
#properties of the data series
print(" shape of table is :",data_series.shape)
print(" index of table is :",data_series.index)
print(" size of table is :",data_series.size)
print("dtypes of table is :",data_series.dtypes) #string is refered object in pandas 
print("length of table is :",len(data_series))

 shape of table is : (3,)
 index of table is : RangeIndex(start=0, stop=3, step=1)
 size of table is : 3
dtypes of table is : object
length of table is : 3

## Escape Sequece

* ' \ ' is considered as the escape sequence for any sentence in python

suppose U want to print the statement `My name is "chidvilas"`using "" ,by default python throws error inorder to say python "" is not ending charecter,we use ' \' such that it will reconnize it as escape sequnce and avoids error

In [102]:
print("My name is \"chidvilas\"") #->> \ make sures to tell python consider next element as string or raw text

My name is "chidvilas"

In [103]:
print('My name is \'chidvilas\'')

My name is 'chidvilas'

In [104]:
#with in the same concept '\n','\t' works