## Sorting a Dataframe

    * we can sort elements in column Ascending and Descending orders
    * we can sort the multiple columns at same time 
    * We can sort multiple columns one Ascending and another Descending alternatively at the same time

#### sort_values : used to sort the elements inside the columns
#### sort_index : used for indexes of table

In [1]:
import pandas as pd
car_df=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\exported.xlsx")
car_df

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625

In [8]:
# sorting a single colunm ascending [both numeric and object]
car_df.sort_values('body_style')

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
72,73,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,180.3,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,35056
189,190,volkswagen,gas,std,two,convertible,fwd,front,94.5,159.3,...,ohc,four,109,mpfi,8.5,90,5500,24,29,11595
128,129,porsche,gas,std,two,convertible,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,37028
172,173,toyota,gas,std,two,convertible,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,17669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,154,toyota,gas,std,four,wagon,fwd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,31,37,6918
154,155,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,7898
155,156,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,8778
109,110,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,...,l,four,120,mpfi,8.4,97,5000,19,24,12440
102,103,nissan,gas,std,four,wagon,fwd,front,100.4,184.6,...,ohcv,six,181,mpfi,9.0,152,5200,17,22,14399

In [10]:
car_df.sort_values('compression_ratio')

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
9,10,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?
29,30,dodge,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,mfi,7.0,145,5000,19,24,12964
84,85,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,14489
117,118,peugot,gas,turbo,four,sedan,rwd,front,108.0,186.7,...,l,four,134,mpfi,7.0,142,5600,18,24,18150
124,125,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,12764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,185,volkswagen,diesel,std,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7995
187,188,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,68,4500,37,42,9495
182,183,volkswagen,diesel,std,two,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7775
192,193,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,180.2,...,ohc,four,97,idi,23.0,68,4500,33,38,13845
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470

In [12]:
# sorting a single colunm desending
car_df.sort_values('make',ascending=False)

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625
199,200,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18950
194,195,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,12940
195,196,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,13415
196,197,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,15985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
3,4,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495

In [15]:
car_df.sort_values('compression_ratio',ascending=False)

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
192,193,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,180.2,...,ohc,four,97,idi,23.0,68,4500,33,38,13845
184,185,volkswagen,diesel,std,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7995
182,183,volkswagen,diesel,std,two,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,52,4800,37,46,7775
187,188,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,171.7,...,ohc,four,97,idi,23.0,68,4500,37,42,9495
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,118,peugot,gas,turbo,four,sedan,rwd,front,108.0,186.7,...,l,four,134,mpfi,7.0,142,5600,18,24,18150
83,84,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,14869
124,125,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,12764
84,85,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,14489
82,83,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,...,ohc,four,156,spdi,7.0,145,5000,19,24,12629

In [14]:
car_df.price

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

### we can sort the multiple columns at same time

In [19]:
car_df.sort_values(['body_style','make']).head(15)

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
72,73,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,180.3,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,35056
128,129,porsche,gas,std,two,convertible,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,37028
172,173,toyota,gas,std,two,convertible,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,17669
189,190,volkswagen,gas,std,two,convertible,fwd,front,94.5,159.3,...,ohc,four,109,mpfi,8.5,90,5500,24,29,11595
69,70,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,187.5,...,ohc,five,183,idi,21.5,123,4350,22,25,28176
74,75,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,199.2,...,ohcv,eight,304,mpfi,8.0,184,4500,14,16,45400
98,99,nissan,gas,std,two,hardtop,fwd,front,95.1,162.4,...,ohc,four,97,2bbl,9.4,69,5200,31,37,8249
126,127,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,32528
127,128,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,34028
167,168,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,8449
168,169,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,9639
170,171,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,11199
2,3,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500

In [ ]:
#We can sort multiple columns one Ascending and another Descending alternatively at the same time

In [23]:
car_df.sort_values(['body_style','make'],ascending=[True,False]).head(15)

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
189,190,volkswagen,gas,std,two,convertible,fwd,front,94.5,159.3,...,ohc,four,109,mpfi,8.5,90,5500,24,29,11595
172,173,toyota,gas,std,two,convertible,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,17669
128,129,porsche,gas,std,two,convertible,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,37028
72,73,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,180.3,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,35056
0,1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,2,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
167,168,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,8449
168,169,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,9639
170,171,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,...,ohc,four,146,mpfi,9.3,116,4800,24,30,11199
126,127,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,32528
127,128,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,34028
98,99,nissan,gas,std,two,hardtop,fwd,front,95.1,162.4,...,ohc,four,97,2bbl,9.4,69,5200,31,37,8249
69,70,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,187.5,...,ohc,five,183,idi,21.5,123,4350,22,25,28176
74,75,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,199.2,...,ohcv,eight,304,mpfi,8.0,184,4500,14,16,45400
190,191,volkswagen,gas,std,two,hatchback,fwd,front,94.5,165.7,...,ohc,four,109,mpfi,8.5,90,5500,24,29,9980

## Sorting by index

In [28]:
car_df.sort_index(ascending=False).head(15)

,Unnamed: 0,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_type,num_of_cylinders,engine_size,fuel_system,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
204,205,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,19,25,22625
203,204,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,six,145,idi,23.0,106,4800,26,27,22470
202,203,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485
201,202,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,8.7,160,5300,19,25,19045
200,201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,16845
199,200,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18950
198,199,volvo,gas,turbo,four,sedan,rwd,front,104.3,188.8,...,ohc,four,130,mpfi,7.5,162,5100,17,22,18420
197,198,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,16515
196,197,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,24,28,15985
195,196,volvo,gas,std,four,wagon,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,13415
194,195,volvo,gas,std,four,sedan,rwd,front,104.3,188.8,...,ohc,four,141,mpfi,9.5,114,5400,23,28,12940
193,194,volkswagen,gas,std,four,wagon,fwd,front,100.4,183.1,...,ohc,four,109,mpfi,9.0,88,5500,25,31,12290
192,193,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,180.2,...,ohc,four,97,idi,23.0,68,4500,33,38,13845
191,192,volkswagen,gas,std,four,sedan,fwd,front,100.4,180.2,...,ohc,five,136,mpfi,8.5,110,5500,19,24,13295
190,191,volkswagen,gas,std,two,hatchback,fwd,front,94.5,165.7,...,ohc,four,109,mpfi,8.5,90,5500,24,29,9980

## .reset_index()

In [34]:
carsub=car_df.groupby(['make','aspiration'],as_index=False)[['engine_location','fuel_system','fuel_system']].count()\
        .sort_values('aspiration') # so main problem here is indexes are in UNORDERED so we wanto order it so we use reset_index()
carsub

             make aspiration  engine_location  fuel_system  fuel_system
0     alfa-romero        std                3            3            3
30     volkswagen        std               10           10           10
28         toyota        std               31           31           31
26         subaru        std               10           10           10
24           saab        std                4            4            4
23        renault        std                2            2            2
22        porsche        std                5            5            5
20       plymouth        std                5            5            5
18         peugot        std                5            5            5
32          volvo        std                6            6            6
14     mitsubishi        std                7            7            7
16         nissan        std               17           17           17
10          mazda        std               17           17           17
1            audi        std                5            5            5
9          jaguar        std                3            3            3
8           isuzu        std                4            4            4
7           honda        std               13           13           13
11  mercedes-benz        std                4            4            4
5           dodge        std                6            6            6
4       chevrolet        std                3            3            3
3             bmw        std                8            8            8
12  mercedes-benz      turbo                4            4            4
31     volkswagen      turbo                2            2            2
29         toyota      turbo                1            1            1
2            audi      turbo                2            2            2
27         subaru      turbo                2            2            2
6           dodge      turbo                3            3            3
21       plymouth      turbo                2            2            2
19         peugot      turbo                6            6            6
17         nissan      turbo                1            1            1
15     mitsubishi      turbo                6            6            6
13        mercury      turbo                1            1            1
25           saab      turbo                2            2            2
33          volvo      turbo                5            5            5

In [35]:
carsub.reset_index() #so we get  elements with orderded index and sorted aspiration
                     #but here main problem is dual index to discard it we use drop index method

    index           make aspiration  engine_location  fuel_system  fuel_system
0       0    alfa-romero        std                3            3            3
1      30     volkswagen        std               10           10           10
2      28         toyota        std               31           31           31
3      26         subaru        std               10           10           10
4      24           saab        std                4            4            4
5      23        renault        std                2            2            2
6      22        porsche        std                5            5            5
7      20       plymouth        std                5            5            5
8      18         peugot        std                5            5            5
9      32          volvo        std                6            6            6
10     14     mitsubishi        std                7            7            7
11     16         nissan        std               17           17           17
12     10          mazda        std               17           17           17
13      1           audi        std                5            5            5
14      9         jaguar        std                3            3            3
15      8          isuzu        std                4            4            4
16      7          honda        std               13           13           13
17     11  mercedes-benz        std                4            4            4
18      5          dodge        std                6            6            6
19      4      chevrolet        std                3            3            3
20      3            bmw        std                8            8            8
21     12  mercedes-benz      turbo                4            4            4
22     31     volkswagen      turbo                2            2            2
23     29         toyota      turbo                1            1            1
24      2           audi      turbo                2            2            2
25     27         subaru      turbo                2            2            2
26      6          dodge      turbo                3            3            3
27     21       plymouth      turbo                2            2            2
28     19         peugot      turbo                6            6            6
29     17         nissan      turbo                1            1            1
30     15     mitsubishi      turbo                6            6            6
31     13        mercury      turbo                1            1            1
32     25           saab      turbo                2            2            2
33     33          volvo      turbo                5            5            5

In [36]:
carsub.reset_index(drop=True)

             make aspiration  engine_location  fuel_system  fuel_system
0     alfa-romero        std                3            3            3
1      volkswagen        std               10           10           10
2          toyota        std               31           31           31
3          subaru        std               10           10           10
4            saab        std                4            4            4
5         renault        std                2            2            2
6         porsche        std                5            5            5
7        plymouth        std                5            5            5
8          peugot        std                5            5            5
9           volvo        std                6            6            6
10     mitsubishi        std                7            7            7
11         nissan        std               17           17           17
12          mazda        std               17           17           17
13           audi        std                5            5            5
14         jaguar        std                3            3            3
15          isuzu        std                4            4            4
16          honda        std               13           13           13
17  mercedes-benz        std                4            4            4
18          dodge        std                6            6            6
19      chevrolet        std                3            3            3
20            bmw        std                8            8            8
21  mercedes-benz      turbo                4            4            4
22     volkswagen      turbo                2            2            2
23         toyota      turbo                1            1            1
24           audi      turbo                2            2            2
25         subaru      turbo                2            2            2
26          dodge      turbo                3            3            3
27       plymouth      turbo                2            2            2
28         peugot      turbo                6            6            6
29         nissan      turbo                1            1            1
30     mitsubishi      turbo                6            6            6
31        mercury      turbo                1            1            1
32           saab      turbo                2            2            2
33          volvo      turbo                5            5            5

## TASK: Convert the MultiIndex columns into 
### ['body_style','engine_location', 'city_mpg_min', 'city_mpg_max', 'highway_mpg_mean']

In [21]:
df_groupby = car_df.groupby(["body_style","engine_location"], as_index=False) \
[["city_mpg", "highway_mpg"]].agg(city_mpg_min=("city_mpg", "min" ),city_mpg_max=("city_mpg", "max" ),highway_mpg_mean=("highway_mpg","mean"))

df_groupby.columns

Index(['body_style', 'engine_location', 'city_mpg_min', 'city_mpg_max',
       'highway_mpg_mean'],
      dtype='object')

In [3]:
df_groupby

    body_style engine_location city_mpg     highway_mpg
                                    min max        mean
0  convertible           front       16  24   26.200000
1  convertible            rear       17  17   25.000000
2      hardtop           front       14  31   28.000000
3      hardtop            rear       17  17   25.000000
4    hatchback           front       16  49   32.171429
5        sedan           front       13  45   30.833333
6        wagon           front       17  31   28.720000

In [22]:
df_groupby.columns

Index(['body_style', 'engine_location', 'city_mpg_min', 'city_mpg_max',
       'highway_mpg_mean'],
      dtype='object')

In [23]:
df_groupby2 = car_df.groupby(["body_style","engine_location"], as_index=False) \
[["city_mpg", "highway_mpg"]].agg(city_mpg_min=("city_mpg","min"), highway_mpg_mean=("highway_mpg","mean"))

In [24]:
df_groupby2

    body_style engine_location  city_mpg_min  highway_mpg_mean
0  convertible           front            16         26.200000
1  convertible            rear            17         25.000000
2      hardtop           front            14         28.000000
3      hardtop            rear            17         25.000000
4    hatchback           front            16         32.171429
5        sedan           front            13         30.833333
6        wagon           front            17         28.720000